Cargo.lock
Cargo.toml
src/main.rs
src/ui_commands.rs

Ok, here are the changes necessary to make it work, at least it compiles. At mentioned in https://github.com/Kethku/neovide/issues/20, I have no way to test if this works.
Key points:
- UI events are notifications. This was kind of hidden from you in neovim-lib by the channel handler, but it's always been this way :)
- I'm using the futures branch of nvim-rs, since that's the future of nvim-rs :) It comes with a tad more ceremony around using tokio, but at least somewhat enables other runtimes.
- I've restricted my changes to `main`, and I did not do error handling or something
- A main point to make the sync channel from std (necessary since you need it in the winit event loop) work with the async fn's is to have it owned by `main` at first, so we can send it off to `start_nvim` …

Port to nvim-rs

---

Cargo.lock
Cargo.toml

Fixes #47.
Note that this error only comes up when translating HTTPS to SSH for git; nonetheless, good to fix (as the branch no longer exists).

Fix nvim-rs dependency

---

src/bridge/events.rs
src/bridge/handler.rs
src/bridge/keybindings.rs

Thanks for writing this awesome project! 
Exploring the code I saw that the `bridge` module make a lot of `.clone`s and owned values when references are enough. This PR fixes what I found.
The commits are very isolated and can be reviewed in isolation.
As a tip, dunno if you knew the tool but [clippy](https://github.com/rust-lang/rust-clippy) pointed many of the issues that this PR fixes.

Remove unnecessary clones and allocations from bridge module

---

src/editor/mod.rs

Avoids allocations and temporary copies of the scrolled data, although it's probably harder to read, unfortunately. I could add comments if desired.
Note: one difference with the previous implementation is that this one clears the grid after itself. The area that the scrolled text will no longer cover will be left with a value of None, and it will be marked as dirty. I did this as the neovim-qt implementation was doing that too, and seemed safer. If this is not desired, I can easily remove it.

Different implementation of scroll_region

---

Cargo.lock
Cargo.toml
src/bridge/events.rs
src/bridge/handler.rs

This PR applies the suggestion made by @KillTheMule in #81, i.e. remove the rest of clones by taking ownership of `Value`.
In the end, the code is cleaner than before but I needed to use a macro to mimic the slice pattern (but taking ownership of the elements). I'm open to rewriting if anyone knows a better way to do something like that.

Take msgv::Value by value in bridge::events

---

src/editor/grid.rs
src/editor/mod.rs
src/renderer/cursor_renderer.rs

Converts `Editor::grid` from a nested `Vec<Vec<GridCell>>` to a `Vec<GridCell>` structure.
Does the same thing with `Editor::dirty`.
I'm opening this pull request just to discuss this as a possible approach. I believe this specific implementation can be improved (maybe by encapsulating a bit more the `grid` itself? Maybe extract `grid` and `dirty` into a separate struct?), but I also think it shows promise.

Idea for linearization of the Editor grid storage

---

Cargo.lock
Cargo.toml
src/bridge/handler.rs
src/editor/mod.rs
src/renderer/cursor_renderer.rs
src/renderer/mod.rs
src/window.rs

Also, no possibility of poisoning, so it removes a bunch of unwraps.
parking_lot is already a transitive dependency for neovide, so this is not adding more dependencies, really.

Switch to parking_lot::Mutex. It is faster and has a better API than the std one

---

.github/workflows/rust.yml
Cargo.toml

- Should fix #105 for macOS
- `Neovide.app` available as an artifact to be downloaded
- `nvim` binary should available in path while executing the App
- Need to run `chmod +x Neovide.app/Contents/MacOS/neovide` after downloading the artifact. Open issue in Github's [upload-artifact](https://github.com/actions/upload-artifact/issues/38) action

Cargo bundle for macOS

---

src/bridge/keybindings.rs

Left a bunch unsupported, as I have no idea how to translate the "Calculator" key, for example, to something Vim understands

Add all missing VirtualKeycodes to the translation function

---

src/bridge/mod.rs

The error messages for having a version of neovim which is too old are not printed to the console. They are logged to file, and only if the `--log` argument is passed.
This PR makes those messages more visible by writing them directly to stderr.

Write nvim version requirement messages directly to stderr

---

src/renderer/caching_shaper.rs

This should fix #153 on Windows but needs testing on Linux and macOS.
This is how it looks on Windows:
I can test this branch on on macOS later if you want. On Linux I don't even know if I can run something using Vulkan thanks to Nvidia 👍 
I also did a test with Quiva as default font for symbols but it didn't mesh well with monospaced fonts.

Shaper includes system symbol fonts into cache

---

assets/neovide.desktop

This PR just adds a `.desktop` file that Linux users can use to start Neovide from their Desktop manager.
We can add this to the AUR for Linux so it's installed there.

feat: add desktop entry for linux systems

---

src/bridge/layouts/mod.rs
src/window.rs

I had a few issues with the way the fullscreen behaviour worked so I made this PR to try and improve it.
I've improved the borderless fullscreen behaviour loosely based on https://discourse.libsdl.org/t/true-borderless-fullscreen-behaviour/24622/11. It works seamlessly on my multi-monitor Windows 10 setup. 
I also added toggleability with Alt+Enter.

Toggleable fullscreen (Alt+Enter)

---

src/bridge/events.rs
src/editor/cursor.rs
src/editor/mod.rs
src/redraw_scheduler.rs
src/renderer/cursor_renderer/cursor_vfx.rs
src/renderer/cursor_renderer/mod.rs
src/renderer/mod.rs
src/settings.rs
src/window.rs

So there's currently a hack in neovide to avoid animating the cursor while typing which relied on calculating whether the travel distance is one character to the right, it works but also disables any one char wide right motion, including hitting `l` in normal mode. A behavior which might be interpreted as a bug to many new comers (i too thought that)
Changes:
1. Adds a neovide setting `cursor_animate_in_insert_mode` _defaults to true_ to allow the user to selectively disable animations specifically in insert mode. Should fix #225 and probably #117
2. Fixes #253 a bug caused by cursor trail sizes over one, where setting any value over 1 will cause the cursor to behave weirdly (animation doesn't end), resulting in a broken cursor
3. Some whitespace/newlines house keeping

Proper setting to disable cursor animation while in insert mode

---

src/window.rs

Rework of the fullscreen toggle to remove unnecessary unsafe calls and use standard fullscreen on macos

better fullscreen toggle and minor cleanup

---

src/bridge/ui_commands.rs
src/window.rs

In order to open a file if there’s changes in current buffer, a user should have `set hidden` in his/her vimrc. This should fix #242
@Kethku i wonder why you stated that it isn't possible with sdl, just an oversight?

Neovide can now open files... with drag/drop

---

Cargo.lock
Cargo.toml
src/bridge/mod.rs
src/settings/from_value.rs
src/settings/mod.rs

I figured that separating the from_value stuff from the main settings module as an auxiliary file would be best. I was able to add unit tests for all but the last two functions of the Settings implementation. Rust still needs a decent sinon type library or more flexible mocking. Would it be best to open up a testing branch for me to merge these into? Feels weird pushing the testing into master, but I guess it doesn't really mess with anything.
Also while writing the test I ran into some locking issues that I want to discuss when setting a value. The fix here ensures that all locks are released:
https://github.com/j4qfrost/neovide/blob/2e01d49b536c889e8a45eecc3979700ec239dfb3/src/settings/mod.rs#L130
Not sure why I would need this, but my test cases were stalling without it.

Settings tests

---

src/renderer/caching_shaper.rs

Instead of using unifont we can use noto sans mono for better unicode support
With `Unifont`
With `Noto Sans`

Better symbol font for linux

---

Cargo.lock
Cargo.toml
src/window.rs

This PR:
* picks up the fix for Kethku/neovide#147
* disables the vulkan debug layer. It was blocking me from running on my Mac with a broken (?) vulkan-sdk install. Neovide runs fine without it, and @aclysma mentioned on gitter that it shouldn't be on in shipping software & having it enabled has significant perf impact.
(@j4qfrost I noticed that neovide is currently using https://github.com/j4qfrost/skulpin, does my PR trample on something you're doing?)

Point skulpin at upstream & turn off Vulkan debug layer

---

Cargo.lock
Cargo.toml
src/bridge/mod.rs

Defaults to searching in PATH if the NEOVIM_BIN variable is not provided. We can also do a check to see if NEOVIM_BIN points to a binary or not, but I think it's safe to assume that the user will manage this.

Add search for nvim in PATH

---

src/renderer/font_options.rs

When debugging a font issue, I noticed that fallbacks are not set correctly. Seems we dropped a `!` in a recent refactor.

Allow font fallback

---

src/renderer/mod.rs

With certain font-configurations, underscores are not drawn on every line.
Locally, setting `set guifont=Deja\ for\ Powerline\ Medium:h11` caused underscores to be hidden on two lines and then displayed on the following three:
Fixing the line height to the nearest integer seems to alleviate the issue.

Fix underscores not displayed on every line

---

src/bridge/handler.rs
src/bridge/mod.rs
src/bridge/ui_commands.rs
src/main.rs
src/settings/mod.rs
src/settings/windows_registry.rs

Fixes this: https://github.com/Kethku/neovide/issues/308#issuecomment-679125311
There is a possibility to add shell environment support by sourcing .zshrc or .bashrc, nut I will only add this on request, since these are dependent on a user's personal environment.

Add all environment variables from .profile

---

src/bridge/mod.rs
src/settings/mod.rs

[issue #281](https://github.com/Kethku/neovide/issues/281) the issue arises mainly because `-h` or `--version` quits the `neovim` instance immediately. Since the user already have `neovim` installed, so echoing `neovim` version back is not logical when user supplies `[-v | --version]`, instead `[-v | --version]` should print `neovide's` version and help. Other thing is to check if we can access `neovim` API before executing any commands on `neovim` instance, because then we can be sure we are accessing a valid instance.

added version info and exit on unknown command line option

---

src/main.rs
src/settings/mod.rs

nevoid can now be run on macOS without spawning a new terminal, it will disown itself on the first run.

macos neovide disown from terminal #402

---

src/window/sdl2/mod.rs

SDL tells the window manager to disable compositing for its windows by
default in order to somewhat improve rendering performance.  This is
unfortunate for a text editor one would be using concurrently with other
programs, because KDE misbehaves with its global taskbar if this is
done, and it also may freeze or otherwise break the display of running
Firefox windows. This misbehaviour affects all SDL windows including
e.g. games such as Factorio.
There is a global switch to ignore all applications making this request
in the KDE compositor settings called "Allow applications to block
compositing", as well as an option in the window rules dialog to do it
for individual windows by class, but we should try to do the right thing
by default. The user can decide to block compositing per-window …

Disable the default-on SDL hint to disable compositing on X11

---

src/renderer/mod.rs

This is a bit of a hack to fix #436, there's surely a better solution but I'm not sure what it is right now.
Rounding the width breaks some drawing of text (one case being where there's a combination of underlined and non-underlined text in a line), possibly due to one system using font shaping for width and another using a constant font width, would require more investigation to track down.

Round up font size to account for draw_image_rect not doing subpixel copying

---

src/window/sdl2/layouts/mod.rs
src/window/settings.rs

As discussed in #388, I have created a new vim setting to differentiate between ANSI and ISO layout to handle the Right Alt/Alt Gr key properly. I added an optional setting `neovide_iso_layout` that can be set to true when necessary.
At the moment, the fix only applies to sdl2. Winit doesn't differentiate between left and right Alt and I don't know how to fix this problem without heavily modifying how the input is handled. 
Because this is potentially affecting many users, I opened a PR with only the sdl2 fix. That way, at least, will be solved for some people. 
Let me know if you have any suggestion.

Add vim setting for ISO layout compatibility (sdl2)

---

src/bridge/events.rs
src/bridge/handler.rs
src/bridge/mod.rs
src/bridge/ui_commands.rs
src/error_handling.rs
src/renderer/fonts/font_loader.rs
src/window/keyboard/token.rs
src/windows_utils.rs

I've removed unused imports, prefixed an unused variable with an underscore and didn't do anything to an unused `pub` function. Also fixed
```
warning: panic message is not a string literal
--> src/error_handling.rs:5:12
|
5 |     panic!(explanation.to_string());
|            ^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(non_fmt_panic)]` on by default
= note: this is no longer accepted in Rust 2021
help: add a "{}" format string to Display the message
|
5 |     panic!("{}", explanation.to_string());
```
After this, there's only the one warning about the unused function ( `build_neovide_command` in `src/bridge/mod.rs` )

Fix clippy, fix font load test

---

src/window/sdl2/mod.rs

This appears to fix some (not all) of the problems that are mentioned in #466

Don't call `.vulkan()` when building the SDL window on macOS

---

.github/workflows/build.yml

This is the standard way to distribute applications for macOS.
It also avoids relying on GitHub to preserve file permissions (particularly +x) when zipping files.
Fixes #466

Use .dmg files to distribute for macOS

---

Cargo.lock
Cargo.toml
README.md
src/bridge/create.rs
src/bridge/handler.rs
src/bridge/mod.rs
src/bridge/tx_wrapper.rs
src/bridge/ui_commands.rs
src/settings/mod.rs

Allows the user to connect to a remote instance of Neovim over TCP using the `--remote-tcp` flag.
Because rust does not have full support for polymorphism, I created the enum type `TxWrapper` to allow either `ChildStdin` or `WriteHalf<TcpStream>` to be used for the connection stream, while avoiding a complicated mess of type parameters. To do this I had to turn some of our implicit dependencies (ie. dependencies of dependencies) into explicit dependencies, but there are no new dependencies. I also adapted some of the functions from `nvim_rs::create::tokio` to work with this new general type.
I have also tried to make it clear in the readme that, without SSH port forwarding or similar, TCP sockets are not secure.
I think that this fixes #50

Remote TCP

---

Cargo.toml

Compiling for apple silicon/m1 only works on 0.39.1

Bump skia-safe to 0.39.1

---

src/main.rs

Now we can see the version and use the help command without opening the neovide GUI. 
If i need to confirm my neovide version it will open the neovide and i dont want it. I just want to see the version.

Version and help without opening the program

---

README.md

Git clones "neovide-git" folder from the AUR, but cd changes the current directory to "neovide" instead of "neovide-git".

Fix typo in Arch Linux AUR installation.

---

README.md

Adds instructions to README.md for arch users on switching branches. This often comes up with Vulkan driver issues, where users are referred to the OpenGL branch as a substitute.

Add instructions for changing branches with PKGBUILD.

---

.github/workflows/build.yml
neovide-derive/src/lib.rs
src/renderer/cursor_renderer/mod.rs
src/renderer/mod.rs
src/window/keyboard/settings.rs
src/window/sdl2/mod.rs

Fix some small problems that appeared as warnings in the `cargo build` output, and were causing the pre-commit git hook (which I had disabled locally) to fail. These were mostly just unused code and improper attribute order.
Of note is `Sdl2WindowWrapper.transparency`, which was set whenever `WindowSettings.transparency` is out of sync with the window's actual opacity, but was never read from so I removed it.

Fix warnings

---

README.md

This PR was created to update the README. It comprises a restructure of the Linux build section (with a few build instructions refactored, namely using `sed` in the AUR from different branch build and adding a section on installing with an AUR helper) and a few minor formatting tweaks.
This PR started due to a request in issue #610 to make a known fix more obvious. While doing that, I decided to see about refactoring the build section a bit more (I've tried to restrict these to separate commits so they can be cherry-picked if desired).
Should close #610

README: Update formatting (mostly, the linux section)

---

Cargo.toml

Update cargo resolver to version 2 to avoid unwanted feature activation.
The package sdl2-sys has features bundled and static-link for target
linux activated, since the cargo resolver version 1 aggregates all
possible features. The newer version avoids this behaviour.
See also:
https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2

Update Cargo Resolver Version

---

src/bridge/mod.rs

This PR does two things:
1) It uses `bash -ic` to call `which` in WSL, which allows .bashrc env to be taken into account (resolves #647)
2) It adds a startup command to neovim to get the interactive PATH and set it, so that other things don't break (e.g. LSP which depends on the server being in the PATH)

Use interactive path for neovim resolution

---

Cargo.lock
Cargo.toml
src/bridge/mod.rs
src/cmd_line.rs
src/main.rs
src/redraw_scheduler.rs
src/renderer/cursor_renderer/mod.rs
src/settings/mod.rs
src/window/mod.rs
src/window/settings.rs
src/window/window_wrapper/mod.rs

This is a draft of integrating clap into neovide. I tried to stick to the existing architecture as much as possible, yet it could be that I overlooked or misunderstood something, so comments and criticism are greatly appreciated.
* Created a file cmd_line.rs which has a `CmdLineSettings` struct. The function `handle_command_line_arguments` does the clap-thingy, builds a `CmdLineSettings` and sticks it into the `SETTINGS`.
* `SETTINGS.neovim_args` was removed and put into `CmdLineSettings` and the appropriate changes were made to the rest of the files.
* The `init_logger` function was moved to `main.rs` (It could probably be moved to a separate file completely...) and it reads `verbosity` and `log_to_file` from `CmdLineSettings` instead of taking them as a parameter.
* The primitive …

Implement CLI parsing with clap

---

README.md
src/window/window_wrapper/mod.rs

This commit will allow users to keep the neovim server running(if neovide started with `--remote-tcp`) by closing the neovide window, and quit both neovide and neovim if the user uses any variant of `:q`.

Fix for #566

---

src/cmd_line.rs

This pr adds environment variables for `--frameless`, `--maximized`. Similar to `--multigrid` env var

Add environment variables for window options

---

src/bridge/events.rs

This fixes event handling from latest neovim, which added z_index to win_float_pos_arguments.

fix: Fix parsing win_float_pos_arguments #714

---

src/renderer/fonts/caching_shaper.rs

Fixes the issue where a control character in a text run would cause the entire blob to be dropped. Now it will just skip the control characters.
This issue can appear at the end of a line when there is e.g. virtual text after the newline character
@PyGamer0 @last-partizan @tpict Please try out this branch and see if it fixes your issues!
Ref #723

Don't drop entire blob when shaping control characters

---

src/editor/mod.rs
src/editor/window.rs

Fixes #743
Fixes #341 (well, non-optionally)
Hello, me again :grin:. My cursor jumps to the bottom line quite often, especially with MultiGrid turned on. Sometimes just pressing "i" is enough to get a white streak across my screen.
This PR is a bit of a hack, but it completely resolves the problem for me.
This PR relies on the following assumptions:
- that the gutter window is always ID 3, and
- that intentionally moving the cursor to the gutter always lands you on column 1.
In my case, both of those assumptions hold, so I will leave this up for discussion!

Fix sporadic cursor jumps (a bit hacky)

---

src/window/window_wrapper/keyboard_manager.rs

If a dead key is entered, `key_event.text` is `None`, but `key_event.text_with_all_modifiers()` is `Some`. Kind of clunky, but this PR checks for that and uses `key_event.text_with_all_modifiers()` accordingly so dead keys can be inputted.

Make dead keys work on macOS

---

src/renderer/mod.rs
src/renderer/rendered_window.rs
src/window/mod.rs
src/window/window_wrapper/mod.rs

Also, I replaced inverse scaling (like 1 / scaling) with natural scaling (like 1 ... 2, what returned by window.scale_factor())
I think easier to work with natural scaling factor and multiplication, instead of inverse scaling factor and division.
It looks fine, and works as expected, but please, review carefully parts where i changed scaling.
Also, instead of passing pair of width/height to handle_new_grid_size i pass LogicalSize. So it's impossible to pass incorrect value.
(Probably, this could be splitted into "just fix" and "refactoring", but i hope it's small enough and can be merged as is)
Refs #771

Fix incorrect initial scaling

---

Cargo.lock

Tested locally on a chromebook machine, seems to work fine. Fixes https://github.com/Kethku/neovide/issues/766. I would just double check with @Shatur before merging 
Side note: I think quite a few of the dependencies are out of date now. Is it possible to add dependabots for rust? if not, I might have to manually take a look at them one day

Update rust-skia to support aarch64

---

src/editor/grid.rs
src/editor/window.rs
src/renderer/rendered_window.rs

This is just renaming `bot` to `bottom` in WindowDrawCommand::Scroll
Small increase in character count, big increase in readability :)

Rename "bot" to "bottom" in WindowDrawCommand::Scroll

---

Cargo.lock
Cargo.toml

@shaunsingh first time you updated only versions in lockfile, second time you updated only versions in Cargo.toml, i reverted both commits, and updated versions and checksums in one commit with.
```
cargo update -p skia-safe
```

Fix broken Cargo.lock

---

src/renderer/fonts/caching_shaper.rs
src/renderer/mod.rs
src/renderer/rendered_window.rs
src/window/mod.rs
src/window/window_wrapper/mod.rs
src/window/window_wrapper/mouse_manager.rs

Basic idea here is to remove scaling from as much app as possible.
Let's make only fonts aware of scaling, everything else is expected to just works.
What do you think? Is it good idea? Could this give us any problems in the future?
The basics are already working, it scales as i expect it to. No artifacts.
It is not mac-specific, to reproduce you need to have `Fira Code` installed, and no `guifont` in vimrc. Then neovide tries to load Fira Code as default font, and with scaling greater than 1, bug happens.
-------------------
- Fix
- Refactor
- No

Refactor scaling code

---

src/renderer/fonts/caching_shaper.rs
src/window/window_wrapper/mod.rs

Fixes resizing windows after starting with `--maximized`.
- Fix
- Codestyle
- No

Fix maximize

---

src/bridge/mod.rs
src/cmd_line.rs
src/main.rs
src/settings/mod.rs
src/settings/window_geometry.rs
src/window/mod.rs
src/window/window_wrapper/mod.rs

While i was researching neovim startup sequence, i refactored it a little.
- Removed multiple calls to functions getting window size
- Now there is only one call, when parsing command line arguments
- After this value is used from SETTINGS
I think this way it is better. @Kethku what do you think?
---------------------
- Refactor
- No
Btw, i suppose no one objects i'm using just lists instead of checkboxes in this template? Github is treating checkboxes as "tasks", and i don't like having "2 of 7 tasks" on my PRs :)

refactor(startup): Use SETTINGS to store window geometry

---

.github/workflows/build.yml

This PR adds an extra step to the Windows pipeline to put the Windows artefact in a `.zip` archive. 
A lot of places (specially companies) has proxies that outright blocks everything ending in `.exe` and this is a neat way to make it a bit easier to distribute from Github to those places.
This change is potentially breaking if there exist update processes that links directly to the artefact, alternatively this could be an addition :)

Put Windows artefact in zip archive

---

src/renderer/fonts/caching_shaper.rs

Fixes font scaling from #387
Fonts are actually in points, not pixels. So we need to convert them.
- Fix
- No

fix(fonts): Fix font scaling (points to pixels conversion)

---

src/renderer/fonts/caching_shaper.rs

On MacOS points and pixels are the same.
@clason please check this
- Fix
- No

fix(macos): Fix scaling on mac-os

---

src/renderer/fonts/caching_shaper.rs
src/renderer/fonts/font_loader.rs
src/renderer/fonts/font_options.rs
src/renderer/mod.rs
src/window/window_wrapper/mod.rs

This is draft attemmt to support `ScaleFactorChanged` event.
I use target branch `fix-scaling`, to show only relevant changes in this branch. I'll change it to main when `fix-scaling` is merged.
Here i refactored CachingShaper to always include `options`, and not `Option<FontOptions>`. And removed Option from few other parts, becouse i was lost in `unwrap`s and `map`s. And this is probably works as expected.
Font size is changing when i change scaling in display settings, but window size does not.
Please take a look at this, try it, maybe you have some ideas for how to make window scale too.
Please, pay close attention to any rust-specific features i try to use here, (like pointers, and dereferencing), i usually work with python, and here i write code with help from langserver, …

Dynamic scale factor updates

---

src/window/window_wrapper/keyboard_manager.rs

This refactoring introduces no changes in behaviour, only moves some code:
- maybe_get_keybinding moved out of handle_event, this allows to call `send(UiCommand::Keyboard ..)` only once, amd make things easier to understand.
- moved private functions to botton of the file, this allows us to see importand parts first and details later.
- Codestyle
- Refactor
- No

Refactor keyboard manager

---

Cargo.lock
src/cmd_line.rs
src/window/window_wrapper/mod.rs

This adds two new command line options to neovide, nemely `-a, --appid <wayland_app_id>` and `-c, --class <x11_class>`, to make both overrideable by the user.
This tries to implement the feature that has been asked for in #704
many thanks for @last-partizan for helping me through this :)

Make waylands app_id and x11s class overrideable

---

src/window/window_wrapper/keyboard_manager.rs

This fixes Shift+Tab mappings (now it works).
This is simpler than variant from @smolck in https://github.com/Kethku/neovide/pull/782
And it works for me. @smolck please take a look, i think shift check in is_control_key isn't required.
Refs #445 
- Fix
- No

fix(keyboard): Fix shift+tab handling

---

src/renderer/fonts/caching_shaper.rs

Providing a wrong font was causing neovide to retry every time to load an
inexistent font, instead just trying to load once at it's setup should
be enough
Maybe this can fix #818

Fix to ensure provided gui font is valid

---

src/window/window_wrapper/keyboard_manager.rs

When window focus has just been lost, key pressed events aren't ignored
I tried to track issue #826, I've found that input are been handled as normal when window lost focus, instead of been ignored, and, because of that, handling unnecessary events (such as Alt+Tab, Super+other keys, etc).
I don't have tested with every combination, but I think it solves the problem, as I have myself been facing this issue while using neovide.

Fix to sending key signals when window focus lost

---

src/cmd_line.rs
src/main.rs

Now process will be disowned on all platforms by default. Can be disabled by `--nofork`. Using `-v` implies `--nofork`.
Closes #485
- Feature (probably)
- Refactor
- Yes (--disowned is changed to --nofork)

refactor: Refactor disowning process.

---

src/main.rs

After #852 passing arguments to neovim (ex. `neovide -- --clean`) stopped working because the `--nofork` was added to the end of the argument list causing the disowned process to ignore it since it comes after `--`. This is repeated indefinitely causing the following situation:
```
$ pgrep -a neovide
237212 neovide -- --clean --nofork --nofork --nofork --nofork --nofork --nofork
--nofork --nofork --nofork --nofork --nofork --nofork --nofork --nofork --nofork
--nofork --nofork --nofork --nofork --nofork --nofork --nofork --nofork --nofork
--nofork --nofork ...
```
The fix is simply to put `--nofork` as the first arg.
- Fix
- No

Fix recursion when using -- to pass args to nvim.

---

src/main.rs
src/window/settings.rs
src/window/window_wrapper/keyboard_manager.rs

it also completely ignores keyboard inputs with D modifier
As already discussed at #763, it introduces `g:neovide_input_use_logo` to toggle between logo input handling or ignoring inputs using this modifier and, because of that, it's a feature to normalize usage with terminals (to what people are used to).
So isn't our problem anymore `<D->` been typed, if that option is active, because it works as any function key when using at insert mode.
I'm sure it can close both #763 and #826
About the code itself, if I've made any mistake about organization or something like that, please let me know
I can include documentation at wiki about the option too

add neovide_input_use_logo to toggle logo handling

---

README.md
src/cmd_line.rs

BREAKING CHANGE: Renamed --multiGrid to --multigrid
BREAKING CHANGE: Removed env var NeovideMultiGrid
- Other
- Yes, it renames --multiGrid to --multigrid and removes NeovideMultiGrid env var
Wiki should be updated after merge. I'll handle it.

fix(cmd_line): Renamed --multiGrid to --multigrid

---

src/window/settings.rs
src/window/window_wrapper/mouse_manager.rs

Fixes touch scrolling by keeping track of a virtual scroll position and only sending a scroll event when that scroll position crosses a the line size boundary.

add better touch scrolling

---

.github/PULL_REQUEST_TEMPLATE.yml
.github/workflows/build.yml

Fixes the pr template to not use todo markers, and fixes an intermittent failure in the windows build and test workflow
- Fix
- No

tweak pr template and fix build pipeline on windows

---

src/bridge/mod.rs
src/bridge/ui_commands.rs
src/editor/mod.rs
src/renderer/mod.rs
src/settings/window_geometry.rs
src/window/window_wrapper/mod.rs

I tried to delay window creation until we have guifont, but that way was too obscure, and i tried something different.
Actually, we don't care when window is created, what we do care about - is when window is resized to it's desired size.
So, this PR moves setting initial size into draw_frame, behind `first_render_pass` boolean flag. And then, instead of resizing grid to window size, resizes window to grid size.
Startup process now looks like this:
```
cargo r -- -vvvv --geometry 80x40 2> >(egrep -i '(Resize|First|font upd|dimens|matched)')
...
TRACE [neovide::channel_utils] redraw_event Resize { grid: 1, width: 80, height: 40 }
TRACE [neovide::renderer::fonts::caching_shaper] Font updated to: JetBrainsMono Nerd Font:h11
TRACE [neovide::renderer] Updating font dimensions: 29x14
TRACE …
```

Refactor startup

---

snap/snapcraft.yaml

This should give neovide permissions to access the appropriate drawing libraries for #870. As a possible long-term enhancement/fix, we could look into adding the permissions for the necessary components and revert the containment to "strict".

Potential fix for #870

---

src/renderer/mod.rs
src/window/window_wrapper/mod.rs

Right now when you change font, window or grid not resized, so window is larger or smaller than picture inside it.
This PR triggers grid resize after font change. Maybe it's better to change window size, but I decided to resize grid (picture), becouse it's simpler in our case.
- Fix
- No

fix: Trigger grid resize after font change

---

Cargo.toml
src/bridge/mod.rs
src/channel_utils.rs
src/editor/mod.rs
src/main.rs
src/renderer/fonts/font_loader.rs
src/window/window_wrapper/mod.rs

This reduces the number of dependencies to 345 (from 391) without any major impact on the code. I can break the commits up into separate PRs if you think that's better.
- Changed `image`: Only use the `ico` feature since that's the only one that's needed.
- Removed `rust-embed`: Was only used for embedding two fonts and an icon. Since it uses a proc-macro it's a rather heavy dependency for what it does. If there are plans to embed more things in the near future you might want to keep this anyway though.
- Removed `crossfire`: Was presumably used because it supports both blocking and async on the same channel. Since  #867 the version of tokio used also supports this so lets use that one instead.
- Removed `regex`: Was only used to check nvims version string, but vim has a built-in version …

Clean up dependencies

---

src/bridge/events.rs

This PR moves those annoying messages on startup from stdout to log (with debug level).
```
Ignored client type property: "methods"
Ignored client type property: "attributes"
```
- Fix
- No

fix(logging): Replace println with debug in bridge/events.rs

---

src/renderer/fonts/font_options.rs

Avoids 
```
warning: unused variable: `points_per_inch`
--> src/renderer/fonts/font_options.rs:94:9
|
94 |     let points_per_inch = 72.0;
|         ^^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_points_per_inch`
|
= note: `#[warn(unused_variables)]` on by default
```
when compiling `neovide` on macOS, which is innocuous but has been bugging me for a while.

refactor(font): conditional compilation on macos

---

.github/workflows/build.yml

Should allow M1 artifacts to be built and published even though `EnricoMi/publish-unit-test-result-action/composite@v1` is broken on M1 due to broken `PyNaCl` dependency.

ci: allow skipping failing publish step

---

src/bridge/mod.rs

In Linux the $PATH is traditionally defined in files like `~/.profile`, `~/.bash_profile`. `~/.zprofile` that are loaded on login.
Invoking the user's $SHELL as a login shell will properly load the WSL $PATH.
This is a potential fix for #693
- Fix
- No

Find nvim in WSL using `$SHELL -lic` to resolve $PATH

---

Cargo.lock
Cargo.toml
src/bridge/mod.rs

When trying to build neovide via `cargo install --git
https://github.com/neovide/neovide` it failed.
The reason was, that the `--git` option by default ignores the
Cargo.lock file and resolves crates version on-demand.
Probably because the master branch of `nvim-rs` tracked, there was
a version mismatch of rmpv that it and neovide used.
Bumped version of rmpv in neovide to 1.0.0 to match nvim-rs.
Refreshed the Cargo.lock file via `cargo update`.
Also, fixed a warning where a variable need not be mut.

updates rmpv (0.4.4 -> 1.0.0)

---

src/editor/style.rs

@Kethku i remember we talked about this, and that time we decided not to fix this, as red default color was provided by neovim.
But, i think that was incorrect decision. We're having access to all required data to make decision about underline color:
- fg color
- special color
- defaults (provided by neovim)
And when selecting special - if current area has explicit guisp - we're using it. If not - we fall back to fg color (becouse this gives better user expirience than using red from neovim, as neovim provides `generic defauls`, not specific for this area).
Closing #300
- Fix
- No

fix: Fixed red color for underline

---

Cargo.lock
Cargo.toml
snap/snapcraft.yaml
src/bridge/create.rs

- Fixes #870 and #831
- No
- switch base snap to Ubuntu 20.04
- Included libxfbcommon and libegl/libgl
I was able to build and install the snap locally with --devmode, However, I wasn't able to install with strict confimenent, since snap can't verify local packages. Maybe we should push to "edge" channel first to test it on other machines.

Fix snap package depdencencies

---

src/bridge/events.rs

Neovim added a new field `line_count` to the `win_viewport` event in
https://github.com/neovim/neovim/commit/086631cd92d7b60f122963f9fd1779583b19004c
Handling that explicitly is a stopgap fix (and likely breaking on older versions of Neovim); the proper fix is not to rely on a fixed number of arguments, since the API contract explicitly allows _adding_ new fields (at the end) to events, or adding new keys to a dictionary.

Adapt to upstream change to win_viewport

---

snap/snapcraft.yaml
src/bridge/events.rs

- Fix
- No
This attempts to fix #953 
The current snap on edge channel works with --devmode. So I added some DE fallback to see if rebuilding with those interface will help.

attempt x11 fix

---

src/bridge/ui_commands.rs
src/window/window_wrapper/keyboard_manager.rs
src/window/window_wrapper/mod.rs
src/window/window_wrapper/mouse_manager.rs

Reports keyboard modifiers correctly for mouse events rather than ignoring them.
Also changes mouse input to report the correct mouse button rather than always left.
- Fix
- No

Add modifiers to mouse events and ensure correct mouse button is reported

---

src/editor/window.rs
src/renderer/cursor_renderer/mod.rs
src/renderer/fonts/caching_shaper.rs
src/renderer/grid_renderer.rs
src/renderer/rendered_window.rs

Now that the renderer just draws the entire line at once, I was able to clean up the draw commands a bit to send the whole line at once rather than sending the text fragment by fragment. This in turn lets me draw the background and then the text on top of the background and relax the foreground clipping to no longer clip character by character. I believe this should make emojis render better among other things.
- Fix
- No

Prevent horizontal text clipping

---

.github/workflows/build.yml

- fix for #946 
Following are my findings regarding this issue
Many projects facing this same issue. But it seems this the intended behavior. 
On download, a zip is dynamically created with all the file contents that were uploaded, which is explained here in upload-artifact repo [readme](https://github.com/actions/upload-artifact#zipped-artifact-downloads).
Workaround:
- Instead of zipping and uploading, now we directly upload the executable which resolves the issue.
REF : [upload-artifact double-zips a zip](https://github.com/actions/upload-artifact/issues/39)

Fix for Windows artifact doublezip

---

src/window/window_wrapper/mod.rs

Redrawing the window when the OS requests it to. Fixes #928.
- Fix
- No

Redraw window when requested

---

src/bridge/ui_commands.rs
src/windows_utils.rs

The old code was using HKEY_CLASSES_ROOT, which requires Admin.
Fixed to use HKEY_CURRENT_USER to work without Admin.
Reference: https://stackoverflow.com/a/29769228/13173256
This emloys two right-click menu (context menu) for files, and background directory (open a directory, right click at an empty place).
It is possible to also add a right-click menu to folder (right click on a folder). Key will be: `Software\\Classes\\Directory\\shell\\Neovide` and . Although I don't use this right-click menu, I would still implement this if it's needed.
PS: I think we should update the readme. A while ago, a person contacted me through email asking for command, which is not documented.
---
If you already register right click menu in previous version of Neovim, open `regedit` and remove these keys:
- …

[windows] Right click menu setup with no Admin

---

.github/workflows/build.yml
Cargo.toml

Github Actions now support macOS 11, this allows building a universal app on Intel VMs.
Instead of the separate `build-m1` workflow, CI will now run `cargo bundle` for x86_64 and aarch64 architectures in a single workflow, and then `lipo` them together.
`cargo bundle` doesn't currently support building universal apps, so this requires a bit of manual hacking on the resulting `.app` bundle.
Self-hosted runners to build for M1 are no longer required.
- Fix
- No

Update CI to build a universal app for macOS

---

Cargo.lock
Cargo.toml

Following the build instructions on M1 causes the following error:
```
thread 'main' panicked at 'Unable to generate bindings: ()', /Users/.../.cargo/registry/src/github.com-1ecc6299db9ec823/skia-bindings-0.40.2/build_support/skia_bindgen.rs:255:39
```
The fix detailed in #1054 by @cyz1901 has been confirmed to work by @Sduby22 and me. I'm submitting this PR to hopefully upstream this fix. The remaining question is whether this upgrade breaks the build on other platforms.
Fix #1054.
Technically yes: `skia-safe` was upgraded from `0.40.2` → `0.42.1`. Under semver all `0.X` changes are breaking, but I haven't observed any API incompatibility between these two versions wrt neovim.

Upgrade skia-safe dependency to build on Apple silicon

---

src/bridge/handler.rs

Related to: #1064 
ParallelCommand was only used on windows but it was imported for every distro
- Refactor
- No

Remove compiler warning on non windows platforms

---

src/editor/style.rs

`Style.special()` was returning foreground instead of default special if `special` was `None`. 
(If that was intended then the test at line 145 should be fixed instead).

Fix special style

---

.github/workflows/build.yml

The previous [PR](https://github.com/neovide/neovide/pull/1074) broke CI because it doesn't install `cargo-bundle` before building.
I have no idea why it worked during my testing, probably caching.
- Fix
- No

Install cargo-bundle when building for macOS

---

src/renderer/grid_renderer.rs
src/renderer/mod.rs
src/renderer/rendered_window.rs
src/window/window_wrapper/mod.rs

- Fix
- No
Transparency is broken (I think since c76945? Not sure tho). This PR tries to fix that.
There are still some issues and I could use some help. 
Mainly:
- Transparency not fully updating after changing `g:neovide_transparency` (it refreshes after toggling fullscreen for example).
I tried doing a redraw or something, but unsuccessfully.
- Some backgrounds maybe shouldn't be transparent? Maybe making only `Normal guibg` transparent would look better? Or just make only black color transparent? (that's what my terminal emulator does afaik, and it looks good)
- What exactly should be semi-transparent? You could make window canvas fully transparent and make line background semi-transparent, but then parts inside window but outside nvim canvas are fully transparent. But if you make …

Fix transparency

---

src/main.rs

Currently, it's impossible to launch Neovide from Finder when using Fish as login shell or when using non-standard environment configs (e.g. system managed by [Nix](https://github.com/NixOS/nix) and [nix-darwin](https://github.com/LnL7/nix-darwin)).
This PR removes hardcoded expectation that `~/.profile` exists or that `$SHELL` is POSIX-compatible.
- Fix
- No

Properly export PATH on macOS when ran from Finder

---

src/bridge/handler.rs
src/bridge/mod.rs
src/main.rs

Supersedes  #1065 
Closes #1064 
As @jeremycostanzo said, ui_command_sender isn't used on linux, so it needs to be cfg-ed away.
Not sure if this is the prettiest way, but it only uses a few `#cfg` and didn't require any refactoring/splitting into windows and linux.

Fix compiler warnings on non-Windows

---

src/bridge/mod.rs
src/cmd_line.rs
src/main.rs

Add back `--verbosity` and `files_to_open`, removed in https://github.com/neovide/neovide/pull/1016
- Fix
- No

Fix cmdline args

---

Cargo.toml

Currently neovide does not compile on Ubuntu (closes #1092).
If the second solution in #1092 is preferred, i.e. having x11 and wayland as features in neovide, I can also do that.
- Fix
- No

Enable default features on winit

---

.github/workflows/build.yml

The universal app bundle building process had some problems that prevented granting Full Disk Access to the app, those being:
- Due to build caching, there was a copy of `Neovide.app` inside the main `Neovide.app`
- Binary after `lipo` contained conflicting signatures, x86_64 segment having no signature, while aarch64 had an ad-hoc signature.
These problems resulted in macOS not being able to remember which binary was granted what permissions, so TCC prompt popped up on every file access. It was impossible to grant Full Disk Access to the app.
This PR removes the redundant copy of the `Neovide.app` and adds force Ad-Hoc codesign of the app bundle after `lipo`.
- Fix
- No

Fix Full Disk Access for universal macOS app

---

src/bridge/mod.rs

Newer versions of Vim/Neovim throw error when using `-complete` with `-nargs=0`
https://github.com/neoclide/coc.nvim/issues/3414
https://github.com/neoclide/coc.nvim/pull/3210

remove "-complete=expression" with -nargs=0

---

Cargo.lock
Cargo.toml
src/settings/window_geometry.rs

Neovide was crashing on exit if you had not run Neovim on Windows previously, and therefore no 'AppData\Local\nvim-data\' directory exists. 
While fixing this I noticed that `XDG_DATA_HOME` was not properly respected on Unix platforms and since I had to modify the same functions that deals with that, I fixed it at the same time.
Fix #1013

Fix for non-existing data directory

---

src/settings/mod.rs
src/settings/window_geometry.rs
src/window/mod.rs

Some of the load and save paths that were broken in pull request https://github.com/neovide/neovide/pull/1111 and https://github.com/neovide/neovide/pull/1099 were fixed. And the JSON is now structured to properly support saving and loading of both position and size data, and is easily extendible for more fields and objects in the future.

Fix window settings load and save

---

src/bridge/ui_commands.rs
src/editor/mod.rs
src/renderer/fonts/caching_shaper.rs
src/renderer/fonts/font_loader.rs
src/renderer/grid_renderer.rs
src/renderer/mod.rs
src/window/mod.rs

Display documentation for the guifont option, and list available fonts in a scratch buffer when the user sets guifont equal to "*".
- Feature
- No

List Available Fonts when guifont=*

---

src/settings/mod.rs
src/settings/window_geometry.rs
src/window/mod.rs

refactor saved settings to be an enum to enable persistence of maximized state
- Fix
- No

Persist Maximized State and Respect Maximized Flag

---

src/main.rs

Trim newlines from end of path on macOS

---

src/bridge/mod.rs

Currently WSL is launched with a hack to launch a temporary interactive shell in order to fix the path inside Neovim, but it leaves all other environment variables unset, and does not correctly load all your login scripts.  See this flowchart from https://shreevatsa.wordpress.com/2008/03/30/zshbash-startup-files-loading-order-bashrc-zshrc-etc/
This  pull request changes that, so that Neovim is launched inside an interactive shell, and all settings and scripts are read correctly, at least I haven't seen any problems on my system. 
I also refactored the command line processing to unify the code paths taken on different systems and to avoid duplicating the code.
Note that there's a tiny problem, it does not necessarily work if you spawn another shell from within your bash scripts, like the …

Run WSL Neovim inside a login shell

---

src/renderer/grid_renderer.rs
src/renderer/rendered_window.rs

Floating windows were not rendered transparent with `neovide_transparency=1.0`.

Fix floating windows transparency

---

src/window/mouse_manager.rs
src/window/settings.rs

- Feature
- Touch scrolling
- Clicking by touch tapping
- Creating a visual selection through touch dragging (hold down finger for a bit and move)
- Yes, please list breaking changes
- Touch input is actually handled now instead of ignored
This PR introduces general touch support (despite the branch name). From what I understood this has been supported in the past already, but was broken by a move to `sdl2` _and back to `winit`?_
While the new setting values (namely `touch_deadzone` and `touch_drag_timeout`) are undocumented yet, I'd be happy to do that in the `Wiki` tab, but I can't seem to edit there. It should probably belong to the `Input Settings` section though.

Touch support (scrolling, click-by-tap, visual selection by dragging)

---

website/config.toml
website/static/CNAME

* Make Zola generate the website for the URL https://neovide.dev
* Create the CNAME file at the root of the static site, as GitHub Pages
expects.
- Other
- No

website: Move to neovide.dev

---

Cargo.lock
Cargo.toml
src/bridge/clipboard.rs
src/bridge/handler.rs
src/bridge/mod.rs
src/bridge/setup.rs

Closes #914 
I decided to hook the `*` register to same remote clipboard (A quick solution). A variable `g:neovide_no_custom_clipboard` is introduced and disable custom clipboard hook.
Tests to be done:
Though it should work with WSL, but I don't have WSL configured. SSH instances, and `same host, same client` are tested.
Edge cases:
Empty clipboard and clipboard not text will returns Error, and neovim outputs `Nothing in register +`.
Haven't done anything related to race condition, I assume it has problem, however never checked. Current PR is suffice.
Note:
1. Because copy issue `rpcnotify`, we need to move into Parallel/Serial command to handle race condition. Race only when record/replay or manually copy many times in a small time frame. Paste don't have this problem, since paste is …

Remote copy/paste

---

src/renderer/grid_renderer.rs

Until now only `Normal guibg` color was made transparent. This isn't correct for floating windows. This PR fixes this.
(It will still work like this for non-floating windows, because IMO it looks better and I don't think there is a defined behavior for that. But it can still be up to debate).

Correctly apply opacity to floating windows

---

Cargo.lock

After merging this PR https://github.com/neovide/glutin/pull/1,
which changed dependency in glutin from Kethku/winit to neovide/winit
we need to update Cargo.lock here.
- Other
- No

chore: Update glutin dependency to use neovide/winit

---

neovide-derive/src/lib.rs
src/bridge/clipboard.rs
src/bridge/handler.rs
src/bridge/setup.rs
src/renderer/cursor_renderer/cursor_vfx.rs
src/renderer/cursor_renderer/mod.rs
src/renderer/fonts/caching_shaper.rs
src/renderer/fonts/font_loader.rs
src/renderer/fonts/font_options.rs
src/settings/from_value.rs
src/settings/mod.rs

Before, a new font was constructed for every character not found in the configured fonts. Now, the system will loop over the loaded fonts after not finding a matching font.
Also reworks the font loader to only store fonts based on font name to encourage this architecture moving forward.
- Fix
- No

Address performance issue in font fallback

---

src/bridge/command.rs

I don't know how about other OS where you using SHELL, but on linux you should
pass arguments like this, or this happens:
```
[src/bridge/command.rs:26] cmd = Command {
std: "/usr/bin/nvim" "--embed README.md",
kill_on_drop: false,
}
nvim: Unknown option argument: "--embed README.md"
```
- Fix
- No

fix: Fix opening files on linux

---

src/cmd_line.rs
src/main.rs
src/windows_utils.rs

Fixes issue where app is still parented to the parent console and closed when that console closes on windows.
- Fix
- No

attach and detach the windows console

---

src/renderer/fonts/caching_shaper.rs
src/renderer/fonts/font_options.rs

To use float font size, define it with dot, example:
monospace:h11 - uses integer size
monospace:h11.0 - uses float font size
---
This adds optional support for float font sizes.
- https://github.com/neovide/neovide/pull/1116#pullrequestreview-862861964
This PR has broken my ideal font size, so i'm adding this as a fix.
It should work seamlessly for anyone, if someone wants integer fonts - with default syntax `h11` gives integer scaling, with `h11.0` fonts will not use fudging.
---
- Feature
- No

feat: Allow float font sizes if requested

---

src/editor/cursor.rs
src/editor/mod.rs
src/renderer/cursor_renderer/mod.rs

- Feature
- No
This adds support for `blend=100` when drawing the cursor. In terminal mode if blend=100 is in the active highlight group for `guicursor` then it makes the cursor invisible, my personal use-case for this is hiding the cursor in nerdtree and similar.
Note that I'm not sure if there is more to `blend` than just making the cursor invisible if its 100, `:help blend` says something about blend level in floating windows but I think the cursor is special, in any case I've only implemented the cursor bit.

feat: add support for blend=100

---

src/bridge/command.rs

This PR resolves #1175 
- Fix
- No
First of all, I got rid of Interactive (`-i`) options in shell. because, If a banner or similar text is output at the start of the shell, the output buffer of the executed command cannot be retrieved normally.
**Example:**
(But, in the case of Windows, the command is executed through `wsl`. It may not be affected by files such as `bashrc`, `zshrc`, `bashenv`, `zshenv`, etc)
And referring to the specification of the `Command` as follows
> * No arguments to the program
> * Inherit the current process’s environment
In macOS, It seems that we do not need to run the command through the shell (with `-c`), but simply execute the run command directly.
This may not be a perfect solution. So, I'd really appreciate it if you could give me feedback.

fix: bridge command

---

src/bridge/ui_commands.rs

This adds a new option, `g:neovide_confirm_quit` (default: `0`), which, when set to `1` or `v:true`, will execute `confirm qa` instead of `qa!` when the window is closed.
Mostly fixes #874, by reducing the potential to lose work. It does not pop up a nice dialog box, of course. This is pretty much the way that nvim-qt does things.
Tested on Linux.
Please let me know if there's a more elegant way to query the option than putting it in an inline script.
- Feature
- No, the option is disabled by default.

Add neovide_confirm_quit option to confirm before quitting

---

README.md
src/bridge/command.rs

This PR resolve #1240 
- Fix
- No
The content in #1217 is getting long, so I'm making this PR with a new alternative.
I hadn't thought of this PR (#1072), so currently `Neovide.app` cannot be run through Finder on macOS.
~~However, this still leaves some problems.~~
~~For example, if neovim is installed through `brew`, it will not run (in Finder) because `nvim` does not exist in the `PATH` variable (default installation path is `/opt/homebrew/bin/`).~~
~~But one thing I'm concerned about is that hardcoding the settings of a 3rd party app has maintenance issues later on.
So, if there is a better way, please give feedback.~~
EDIT: Thank you, everyone. I removed direct hardcoding of brew to `PATH` and added a way to solve this problem instead.

Fix: Neovide.app not working in Finder 

---

src/renderer/cursor_renderer/mod.rs
src/renderer/grid_renderer.rs
src/renderer/mod.rs
src/window/mod.rs

- Feature
- No
Hi! I'm really enjoying Neovide! This PR changes the way the cursor is rendered when the editor window is unfocused. If the cursor shape is set to block, then when the window loses focus the cursor will be drawn as an outline. This provides a visual cue that can be easier to notice than other cues like highlighted window borders or title bar because the user tends to focus on the cursor. After using Neovide for a bit I have realized that I rely on the cursor rendering cue - I've been typing into the wrong window much more often recently.
There are still some tweaks that could be made. I have not added tests yet, and I think the outline is a little too thick. I would appreciate any feedback, and I will try to make updates accordingly.
Fixes #1253

Render block cursor as an outline when window is not focused

---

src/renderer/mod.rs
src/renderer/rendered_window.rs

Fixes #1265.
- ~~Should there be different configuration values for the X and Y amount of blur values? (see https://github.com/neovide/neovide/issues/1265#issuecomment-1115091016)~~
- Feature
- No

Add configurable blur amount

---

Cargo.lock
Cargo.toml
README.md
src/bridge/clipboard.rs

Switch to [alacritty/copypasta](https://github.com/alacritty/copypasta). This adds Wayland support without XWayland requirement. Also seems to have less dependencies than abroad.
Tested manually using X11 backend as clipboard has no tests - so I might be missing something.
Fix
No

fix(bridge): switch to copypasta clipboard provider

---

.github/workflows/build.yml

- Fix
Tests failing on Windows #1375
- No
this occurred due to choco installing nvim in different location and not adding env path correctly.
Because of that, this test (test_read_initial_values ) failed.
since we are using std::process:exit(1), program exits in middle when it's not able to find nvim exec. 
Thats why when this particular test failed no useful error msg or info shown. maybe future refactoring!!

GA cargo test fail fix for windows

---

src/window/keyboard_manager.rs
src/window/settings.rs

By default on MacOS pressing a key combination containing an Alt key produces a special character:
<Alt+s> -> ß
<Alt+v> -> √
...
This is really unfortunate if you want to use those key combinations as shortcuts and usually this case has to be separately handled by the app.
This commit introduces a new configuration flag `neovide_macos_alt_is_meta`. When the flag is set to true then all the
<Alt+key> combinations are treated as shortcuts with no extra character modifications, i.e. pressing `Alt` and `s` indeed emits a `<M-s>` shortcut.
Fixes #1046 
No, as far as I can tell

Alternative Alt + character handling for MacOS

---

README.md

Arch Linux has official packages now, these new instructions reflect that.
Also there was duplicated/conflicting instructions for building from the AUR. I really think it's better to scrap all that and let the Arch Wiki help people build packages if they don't know how to already, upstream project README's aren't a good home for detailed instructions on how to use a distro.

Fixup Arch Linux instructions

---

.github/workflows/build.yml

The linux archive ships with un-necessary dir's, 
```
kar@earth:~$ tar -tf Downloads/neovide.tar.gz
./target/release/neovide
```
This patch removes them & archives just the binary
- Fix
- No

ci: remove unncessary dirs in linux artifact

---

Cargo.lock
Cargo.toml
src/cmd_line.rs

- Fix
#1399
- No
Currently tested against mac and windows os.
for some reason enclosing singlequotes around filepath doesnt worked as expected as mentioned by aJuvan. so went with escaping space with backslash.

macos: open filepath which contains spaces correctly

---

src/bridge/setup.rs

[Clipboard providers are only loaded once by Neovim](https://github.com/neovim/neovim/issues/8017), causing the previous code to use an obsolete channel id when reconnecting to a remote nvim instance.
Fixes #1329.
- Fix
I hope not.

Clipboard: Read channel id from nvim variable

---

.config/nextest.toml
.github/workflows/build.yml

Should be faster and require less fiddling with unstable options. Also we finally get actual real output of failed builds now, yay.
- CI QoL feature
- No, the program itself didn't change

Switch to nextest as test runner

---

.github/workflows/build.yml

Stripping the binary is drastically reducing it's size! Thus saves a lot of space for the user! Closes #1041 
```
kar@earth:~/Downloads$ du -sh neovide
95M	neovide
kar@earth:~/Downloads$ strip neovide
kar@earth:~/Downloads$ du -sh neovide
19M	neovide
```
- Feature
- No

ci: strip linux artifact

---

src/window/mod.rs

- Fix
- No
Changes how the detection of window resizing works. Previously relied
on hardcoded 800 x 600 value, which was not always correct on MacOS, or
rescaling by the scaling factor, which was not always correct on Linux.
The physical size of the window is now stored right after the window is
initialized, and this value is used whenever we check for window
resizing.
I have tested this with `WINIT_X11_SCALING_FACTOR` set to 0.8, 1.0, 
1.5, 2.0, and 2.1, and observed seemingly-correct behavior on Linux,
(appropriate response to `--geometry` flag, no panics), so I believe
that this closes a number of scaling bugs. I also have a Macbook on
which I was able to reproduce #1216, and this …

fix: Change how window resize detection works

---

src/window/settings.rs
website/docs/configuration.md

Changes the default for use_logo for MacOS to avoid confusion with new users. 
See https://github.com/neovide/neovide/issues/1263

Changed default for use_logo to true for MacOS

---

src/settings/window_geometry.rs

- Fix
- I honestly don't know. but i don't think so.
I found when i was compiling the v0.9.0 on Windows it says:
```
error[E0658]: use of unstable library feature 'bool_to_option'
--> src\settings\window_geometry.rs:89:26
|
89 |                         .then_some(grid_size)
|                          ^^^^^^^^^
|
= note: see issue #80967 <https://github.com/rust-lang/rust/issues/80967> for more information
error[E0658]: use of unstable library feature 'bool_to_option'
--> src\settings\window_geometry.rs:96:26
|
96 |                         .then_some(position)
|                          ^^^^^^^^^
|
= note: see issue #80967 <https://github.com/rust-lang/rust/issues/80967> for more information
For more information about this error, try `rustc --explain E0658`.
error: could not compile …
```

small fix for unstable library feature

---

src/bridge/ui_commands.rs
src/window/settings.rs
website/docs/configuration.md

- Refactor
- No
This is the default behaviour in nvim-qt. So enabled it by default.
#1247 - original PR with flag.

Enable confirm quit by default

---

Cargo.toml

Helps further slimming of the binary. 
Info:
1. https://doc.rust-lang.org/cargo/reference/profiles.html#strip
2. https://github.com/johnthagen/min-sized-rust#optimize-for-size
- Feature
- No

fix(cargo.toml): rm debug symbols in release build

---

src/cmd_line.rs
src/window/mod.rs
website/docs/command-line-reference.md

- Feature
- No
Adds support for configuring the **instance** part of the x11 `WM_CLASS` property.
I basically just copied the code for the `x11-wm-class` config option and changed the name (`x11-wm-class-instance`). So, this will allow configuration via the command line or an environment variable.
Previously, https://github.com/neovide/neovide/pull/834 added support for explicitly setting the **class** part of the x11 `WM_CLASS` property. The **instance** part was hardcoded to be `neovide`. But, as of the [icccm specs for this property](https://www.x.org/releases/X11R7.6/doc/xorg-docs/specs/ICCCM/icccm.html#wm_class_property):
> Resources that are specified by instance name override any resources that are specified by class name
This means that systems which adhere to this spec will not …

Make x11 WM_CLASS property's instance part configurable

---

src/window/mod.rs
src/window/settings.rs
website/docs/configuration.md

- Feature
- No
This is to lower the load when the window is not in use.
See #1310.

Detect when the window is not in focus and lower the frame rate

---

src/bridge/events.rs
src/editor/mod.rs
src/editor/style.rs
src/editor/window.rs
src/renderer/grid_renderer.rs
src/renderer/mod.rs
website/docs/configuration.md

- Feature
- Fixes #764 
- No
This overhauls the drawing of underlines and actually implements the
undercurl that was simulated with underdashes before.
Implemented in this PR:
* underline
* underdouble
* underdashed
* underdotted
* undercurl
* Previously the underline thickness was proportional to the stroke width. This led to weird aliasing artifacts when drawing lines (especially dashes and dots) and isn't in line with how most other terminal emulators handle this. With this PR, all the lines are pixel-perfect and 1px thick. If desired, it'll be easy to add a configuration option to make it possible to configure the line thickness, but I don't recommend making it proportional to the text itself.
* The undercurl looks (in my opinion) nice, but I don't really know what I'm doing here. I'm …

Handle different underlining styles supported by neovim

---

src/bridge/events.rs
src/renderer/grid_renderer.rs

- Feature
- Ish, removes the effect of `g:neovide_floating_opacity` at least for the grid renderer
This implements usage of the `blend` option in the style in `grid_renderer`. It _seems_ to match up with `winblend` and obey local vs global options but actually testing it is proving to be quite difficult, and I don't fully understand how the drawing actually works (`RenderedWindow::draw` doesn't seem to actually do anything with its opacity for example).
So far it seems to work correctly for `nnn` in picker mode, but telescope is acting weird: when neovim is doing the drawing it kind of works in that the search box respects the transparency but nothing else does, in multigrid mode it …

Implement blend options for grid

---

src/window/mod.rs

- Fix
- No
Previously the window would be resized at startup even if it is remembered to be maximized.
This PR fixes that by adding a new field in `GlutinWindowWrapper` to record whether the window is really maximized at startup instead of only reading from `CmdLineSettings`.

Fix unwanted resizing at startup when the window is remembered to be maximized

---

website/docs/configuration.md

- No
This PR adds the previously undocumented option to hide the mouse cursor when typing to the docs.

Added hide mouse when typing configuration

---

Cargo.lock
Cargo.toml
src/cmd_line.rs
src/dimensions.rs
src/frame.rs
website/docs/command-line-reference.md

Uses clap 4.0 in order to make adding new arguments way, way cleaner. Would be very happy if someone with a specialized usage of Neovide's CLI could actually test this, the testsuite ran through but that doesn't mean anything.
- Refactor
- No (practically, theoretically arguments passed to NeoVim have been reordered a bit)

Clean up cmdline handling

---

src/cmd_line.rs
src/main.rs
src/window/mod.rs
website/docs/command-line-reference.md

- Feature
- No
Maybe fixes #1248, by allowing the user to turn VSync off if not needed/automatically does so if creation fails. Do not merge until some confirmations on that come in, as I'm again running blind here.
Open questions:
- Should we automatically retry without VSync if window creation fails and the error string contains `vsync`? (maybe we can add spaces around it, though I'm more for the general if we should to so thing)

Make vsync configurable

---

src/renderer/mod.rs
src/window/mod.rs
src/window/settings.rs

- Feature
- No
I tried to implement the scaling proposed in #1301. I decided to use an additional factor to the os_scale_factor.
Example for using the new scale_factor with key bindings:
```
let g:neovide_scale_factor=1.0
function! ChangeScaleFactor(delta)
let g:neovide_scale_factor = g:neovide_scale_factor * a:delta
endfunction
nnoremap <expr><C-=> ChangeScaleFactor(1.25)
nnoremap <expr><C--> ChangeScaleFactor(1/1.25)
```

Introduce scale_factor option

---

src/window/keyboard_manager.rs

- Fix
- No
---
Previously (introduced in #1483) some of the special keys (namely `<` and `|`) are mistakenly formatted with a `S-` prefix, which has caused problem in some plugins and Neovim itself (see #1539 and #1542 ).
This PR fixes that by
- separating the formatting of normal keys (which should always be prefixed with `S-` if other modifiers are pressed, aka `use_shift = true`) and special keys (in which some should be but some others should not), and
- introducing a new return value for `is_special` function indicating whether `S-` prefix should be used for this special key.
---
Also during this I've found several other problems in the `keyboard_manager` module. I will open another issue for these.

Fix key string formatting for special keys

---

src/window/keyboard_manager.rs

According to `:help key-notation`, `<CR>` stands for carriage return, which is `\r`.
```
notation	meaning		    equivalent	decimal value(s)
----------------------------------------------------------------------- ~
<CR>		carriage return		CTRL-M	 13	*carriage-return*
<Return>	same as <CR>				*<Return>*
<Enter>		same as <CR>				*<Enter>*
```
This should fix #992.
- Fix
- No

Fix carriage return in keymapping

---

src/cmd_line.rs
src/dimensions.rs
src/settings/mod.rs
src/settings/window_geometry.rs

#1583 caused the last saved window size to no longer be read or used at startup. The `parse_window_geometry()` function is now only used by the parser for the `Dimensions` struct, which is only used if `--geometry` is passed. If that's the case, though, it'll simply use the parsed command line option instead of using the last saved size.
This PR refactors the `parse_window_geometry()` function into two separate pieces--
1. A new function `last_window_geometry()` has been added that attempts to use the last saved window geometry but falls back to the default. This function is used as the default value expression for the `geometry` command line argument/setting.
2. `parse_window_geometry()` now _only_ parses a command line geometry value (like `100x50`). The diff for this looks worse than …

Fix default window geometry to use the last saved value (broken in #1583)

---

src/cmd_line.rs

- Fix #1608
- Yes
- Command line args are actually usable now
This might have some serious implications, to be specific with shell injections. So don't merge just yet.

Don't run shlex on the cmdline args on Woe

---

Cargo.toml
src/bridge/command.rs
src/cmd_line.rs

- Fix
- No
Escaping commands breaks passed commands containing multiple words, which are often used like `nvim -c 'echo "test"'`. Command arguments are passed to TokioCommand, which does not need escaping.

Only escape commandline arguments on macos targets

---

Cargo.toml
src/bridge/command.rs
src/cmd_line.rs

This reverts commit 12b3cee9cce3eb8d20c87709808a5c2ba80f878f.
- Fix
- Yes, #1633's original issue is back again

Revert "Only escape commandline arguments on macOS (#1633)"

---

Cargo.lock
Cargo.toml
src/main.rs

- Feature
- No
I added a panic hook that appends the backtrace to a log file in the current directory so that there is some clue as to what happened when neovide crashes. 
It works by attaching a panic hook at the beginning of `main()`. The original main function has been moved to `protected_main()`. I moved it here for now as I was not sure how to integrate the hook into `main()`'s documentation.

Save backtrace to file on panic

---

Cargo.lock
Cargo.toml
src/renderer/fonts/font_options.rs

The documentation encourages the use of `\` to escape spaces, and there's no way to escape `_` (underline), in the current main branch, it's not possible to load fonts containing it in the name. 
- Fix
- No

Allow use of fonts containing `_` in the name

---

Cargo.toml
src/bridge/command.rs
src/cmd_line.rs

Fixed the signature of the macos version

Only escape commandline arguments on macOS take 2

---

src/renderer/rendered_window.rs

- Fix
- `blur()` return `None` if both x & y blur are 0. I couldn't find any doc on this but I assume this is because a sigma of 0 makes a division by 0 error. Instead of crashing straight away via `unwrap()`, it now simply does nothing (i.e. doesn't blur) if `None` is returned. 
- Note that interestingly when only one of x or y blur is set to 0, it does not return `None`.
- No

Neovide crashes when both x & y blur are set to 0

---

Cargo.lock
Cargo.toml

- Prophylaxis. It updates the source from which the `nvim-rs` dependency is pulled from to the official version. 
- All necessary functionalities have made their way into the release version.
Using the release version results in a simpler and safer dependency update procedure. It's also a step closer to releasing neovide on crates.io, since no git repo dependencies are allowed.
- No

use nvim-rs release version

---

website/docs/troubleshooting.md

- No
I investigate it further and found that's may because X11 don't support mixed refresh rate monitors well, and that's the reason in my case, I demonstrate it in [`troubeshotting.md`](https://github.com/fecet/neovide/blob/main/website/docs/troubleshooting.md).
This should work for [#1634](https://github.com/neovide/neovide/issues/1634), and maybe for [#1312](https://github.com/neovide/neovide/issues/1312)

Add documentation about #1634

---

rustfmt.toml

- No
This PR adds a `rustfmt.toml` file to use `rustfmt` with it's default values which conforms to the formatting config neovide is using.
This allows contributors to format-on-save with their rust formatter more easily. As currently, a system-level rustfmt configuration that differs from the defaults will cause formatting changes. So this PR **fixes facilitation of staging/pushing without formatting**.
As an alternative to an "empty" file we could generate the full default config using `rustfmt --print-config default` which would result in:
<details>
<summary><code>rustfmt.toml</code></summary>
```toml
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
indent_style = "Block"
use_small_heuristics = "Default"
fn_call_width = 60
attr_fn_like_width = 70
struct_lit_width …
```

Add rustfmt.toml

---

src/bridge/command.rs
src/editor/cursor.rs
src/editor/draw_command_batcher.rs
src/editor/style.rs
src/frame.rs
src/renderer/cursor_renderer/cursor_vfx.rs
src/renderer/cursor_renderer/mod.rs
src/renderer/mod.rs
src/renderer/rendered_window.rs

- Codestyle
- Refactor
Fixes all the fluff generated by Clippy. Since there are so few warnings, imho it is best to just fix them, regardless of whether they are all important to neovide.
This will allow to extend the workflows to get more expressive reporting of clippy warnings and thus better detect shortcomings and improve overall code quality.
- No

Resolve clippy warnings

---

src/bridge/command.rs

**Problem**: When neovide is launched from a terminal on MacOS, the $PATH of the launching environment is not preserved due to use of the `-l /--login` option for shell commands.
This causes problems for me, because when launching neovide from CLI with an activated conda python environment, I would like the PATH be preserved from my terminal session so that the pyright language server starts with the desired python interpreter.
**Solution:** This solution is based on j4qfrost's work from https://github.com/neovide/neovide/pull/309, but it seems like the functionality was lost somewhere along the way :D 
So in this PR, I propose using the `--login` option for launching shells if and only if we are launching not from a terminal.

Preserve PATH when launching from terminal on MacOS

---

website/docs/configuration.md

https://github.com/neovide/neovide/issues/1211#issuecomment-1037048651 
the colon is required for the parser to pick up the option
- No

Update configuration.md doc to reflect reality

---

website/docs/configuration.md

The previous version says to use `vim.g.neovide_transparency_point` which gives an error. To match with the VimScript version, this should be `vim.g.transparency` instead (which does work).
- No

Fix Lua instructions in Background Colour

---

.github/workflows/build.yml
.github/workflows/lint-app.yml
.github/workflows/snap.yaml
.github/workflows/test-results.yml

- Codestyle
- Refactor
- No
This PR contains refinements and enhancements that can be made to my recent workflow-related commits. It's things I noted down while doing DevOps work on similar GitHub actions afterwards.
result: https://github.com/tobealive/neovide/actions/runs/4275873794
- Use cache prior to clippy, as this step is sped up as well if there is a cache hit (~4min vs 30s).
- Call reusable linting workflow instead of re-authoring the linting steps in the build action. This was already intended in the original renovation, which is why `workflow_call` was added as part of the `on` block.
- Update the artifact upload condition -> Check if there is a second artifact; instead of assuming there is none on macOS and others have one.
- Update test result publishing
- Publishing on Mac …

Refine workflows

---

src/bridge/command.rs

- Fix
- No
On mac, the `--neovim-bin` and `$NEOVIM_BIN` settings were getting ignored and it was always falling back to `which nvim`. In digging in, I found a few bugs. 
1. The `platform_exists()` function was shelling out to an `exists` command to see if the provided vim could be found. But the `exists` command only exists on Windows. For Mac, calling `Path::new(&bin).exists()` is the better choice than shelling. And as a side note, if a login shell has slow rc files, it impacts startup times for neovide so avoiding that is a bonus.
2. Second, while testing I was using a minimal shell with hardly any environment variables and that was causing crashes. Elsewhere when getting the `$SHELL` var there was a fallback, but in the `nvim_cmd_impl()` function there was just a bare unwrap that was …

Fix mac startup issues

---

src/editor/mod.rs

Floating windows with bottom or right anchors need to be re-positioned when they are resized.
This fixes https://github.com/neovide/neovide/issues/1584, at least the which key part of it. I have not managed to reproduce any other of the issues mentioned.

Update the window float position when resized

---

website/docs/installation.md

A documentation fix. The bundle output needed to be capitalized, and it was pointing to the wrong `Applications` path. I also turned the whole thing into a shell command like the others, but I can change it back if desired.
No

Fix MacOS bundle instructions

---

src/bridge/events.rs

- Fix
- No
Fixes #1798
Fixes https://github.com/neovide/neovide/issues/1804
This fixes an index out of bounds panic because neovim nightly added a new argument to the `win_viewport` event. 
Tested with nvim versions nightly `v0.9.0-dev-1230+gd1e0f7454` and stable `v0.8.3`

Fix parse additional parameter for `win_viewport` event

---

src/dimensions.rs
src/renderer/cursor_renderer/mod.rs
src/renderer/grid_renderer.rs
src/renderer/mod.rs
src/renderer/opengl.rs
src/settings/window_geometry.rs
src/window/draw_background.rs
src/window/keyboard_manager.rs
src/window/mod.rs
src/window/mouse_manager.rs
src/window/renderer.rs

- Refactor
This moves the Glutin context creation to it's own file. It also passes the winit window around rather than the whole context, so that the code mostly becomes dependent on winit rather than glutin. 
The only direct reference to glutin is in the new `opengl.rs` file, but the context is still used outside of that, so some of the code is still dependent on it at an interface level.
This is done mostly to make it easier to review my upcoming render changes. But it should also be quite easy to switch over to not use a forked version of Glutin anymore. The new Glutin versions, no longer depend on winit, so we can use our own version of it. Instead we could directly do something similar as the Glutin winit module https://github.com/rust-windowing/glutin/tree/master/glutin-winit/src
- …

Encapsulate glutin

---

src/bridge/events.rs
src/editor/mod.rs
src/editor/window.rs
src/renderer/cursor_renderer/mod.rs
src/renderer/rendered_window.rs

- Fix
Replaces the old viewport handling with the new scroll_delta event so that we can get actually correct smooth scrolling.
Yes, it disables the smooth scrolling for viewport events which do not have the scroll_delta field. This way we only do it if we know it is correct.

Use new scroll delta field in viewport event for smooth scrolling

---

src/window/mouse_manager.rs

Calls [nvim_input_mouse()](https://neovim.io/doc/user/api.html#nvim_input_mouse()) with `button = "move"`.
Currently, it always emits the events, but IMO it should not emit the events if ["mousemoveevent" option](https://neovim.io/doc/user/options.html#'mousemoveevent') is not enabled. How should we achieve this behavior?
- Feature
- Yes, emits new event

[Feature] Support mouse hover (emit mouse move event)

---

src/bridge/command.rs

A fix for a bug introduced in #1758 where opening Neovide from Finder (i.e. directly running the .app) when using the fish shell as your $SHELL fails. Running `neovide` from a terminal works fine.
Previously (in 0.10.3), Neovide would always run `$SHELL -lc "which nvim"` on macOS to find the `nvim` binary. After #1758, it now runs `$SHELL -c -l "which nvim"` only if the TERM environment variable is not set. `bash` and `sh` do not care about the order of the `-c` and `-l` flags, but `fish` does (I haven't tested other shells). This fix simply reorders those flags, fixing the issue.
No

Fix opening from Finder in macOS

---

src/window/mod.rs

- Fix
- No
With two monitors and the secondary monitor on the left of the main monitor, neovide would always be positioned on the top left instead of the previous position.
On `src/window/mod.rs` line 405, `window.outer_position().ok()?` will always return `PhysicalPosition { x: 0, y: 0 }`. I assume this is because window hasn't been positioned at this point. This led to neovide believing window isn't visible on the current monitor and hence repositioned it to the top left of the current monitor.
Use `previous_position` when possible. This fixed the bug.
I'm using KDE with KWin so this might be a KWin specific problem. But this PR shouldn't break anything as it always falls back to …

Fixes window position not being remembered on multi-monitor

---

src/event_aggregator.rs

Mutex is not needed; Unused THREAD_SENDERS

---

src/bridge/command.rs

- Fix
This PR prevents an additional console window from appearing when starting in `--wsl` mode.
- No

Prevent wsl console window shown

---

Cargo.lock
Cargo.toml
src/cmd_line.rs
website/docs/command-line-reference.md

This disables srgb on Linux and macOs to fix issues with wrong colors being rendered on Wayland with Nvidia. 
It's still enabled on Windows by default  to work around https://github.com/neovide/neovide/issues/907. 
Note that the actual rendering is always non-srgb due to the options we pass to Skia. Enabling srgb only enables the support, so it should really not be needed. 
Disabling it fixes a bug on Wayland with Nvidia cards where the colours are rendered wrong. 
This also adds the full pair of parameters `--srgb`, `--nosrgb`, `--vsync` `--novsync`. So that you always can override what's set in the environment variables. The implementation is not the best due to missing support in clap, see https://github.com/clap-rs/clap/issues/3146 and https://github.com/clap-rs/clap/issues/815 …

Disable srgb on Linux and macOS

---

src/bridge/events.rs

Include the event name and the full set of parameters when invalid events are received from Neovim.

Improve error reporting for invalid UI events

---

src/cmd_line.rs
src/window/mod.rs
src/window/settings.rs
website/docs/command-line-reference.md

Fix: #1885 changed the handling of `--noidle` flag, which caused the behavior to be flipped (so we had `no_idle=true` by default).
I changed the name of the variable and it's usage to reflect the actual behavior.
I also improved the documentation for that option.
Technically yes, relative to current main.

Fix `no idle` behaviour

---

Cargo.lock
Cargo.toml
src/editor/mod.rs
src/main.rs
src/profiling/mod.rs
src/profiling/profiling_disabled.rs
src/profiling/profiling_enabled.rs
src/renderer/cursor_renderer/mod.rs
src/renderer/fonts/caching_shaper.rs
src/renderer/grid_renderer.rs
src/renderer/mod.rs
src/renderer/profiler.rs
src/renderer/rendered_window.rs
src/window/mod.rs

This add profiling support through the [Tracy Profiler](https://github.com/wolfpld/tracy)
To use the profiler you can use the `profiling` or `gpu_profiling` feature, for example
`cargo run --features gpu_profiling`, just remember to launch Tracy first and wait for the connection. It's also helpful to add `--noidle` to better stress the system, and in some cases to disable vsync with `--novsync`
I have also added a few profiling events, that covers most of the basic frame loop. 
Below is a sample, with my screen refresh rate set to 60, matching the default 60 FPS that Neovide tries to maintain. On the surface it looks good, all frames are close to 16.66 ms. But if you look closely it's constantly missing the vsync (over 17ms), followed by a shorter frame to catch up. This will be fixed …

Add profiling support through Tracy Profiler

---

src/settings/config.rs

fix(config): Don't show error when config is missing, instead just log it

---

Cargo.lock
Cargo.toml
src/main.rs
src/renderer/opengl.rs
src/renderer/rendered_window.rs
src/window/draw_background.rs
src/window/keyboard_manager.rs
src/window/mod.rs
src/window/renderer.rs

- Fix
This may break ime support. Not sure, this needs to be tested.

Update to use new upstream unified keyboard branch

---

src/renderer/fonts/caching_shaper.rs

- Fix
- No
Fixes #1852
With linespace set to 14, 
Before:
After:

Center the line by adding half of linespace to y_adjustment

---

website/docs/installation.md

In the recent [git migration](https://archlinux.org/news/git-migration-completed/), Arch has merged the "community" repository into "extra". This PR is just to update the name and link in the install steps :) 
Documentation
No

Fix broken link - Change Arch repository to extra

---

src/renderer/mod.rs
src/renderer/opengl.rs
src/window/mod.rs
src/window/update_loop.rs
src/window/window_wrapper.rs

- Refactor
This splits the `window/mod.rs` into `update_loop` and `window_wrapper`. The opengl window creation has also been split into two functions, the actual window creation and the context creation.
This will make it easier to review the render loop changes in #1870, and to allow some platforms to run in a thread while other platforms don't. 
- No, functionally there are no changes.

chore: Extract window_wrapper and the update loop to their own modules

---

.github/workflows/build.yml
.gitignore
Cargo.lock
assets/neovide.desktop
ubuntu-builder/Dockerfile
ubuntu-builder/build-appimage
ubuntu-builder/build-dockerimage
ubuntu-builder/run

The appimage is now built with the oldest available Ubuntu release 20.04, for maximum compatibility. We could go even older than that, but the Github CI does not support it. 
Furthermore, we use `--locked` for building to ensure that the dependencies are correct. 
A `.zsync` file is added to support auto-updates with for example https://github.com/TheAssassin/AppImageLauncher
Note in order to be able to upload to the appimage hub we need to package this https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps, built with the creator https://www.freedesktop.org/software/appstream/metainfocreator/#/guiapp. I have not done that, since we need some nice screenshots and other information. Could someone do that, and I will apply it here?
Then this …

Fix AppImage support and Dockerfile for testing

---

src/window/keyboard_manager.rs

- Fix
A dead key followed by space will usually result in the character itself. However, Neovide resolved this wrongly, and always treated space as a special key, so the sequence was resolved as space instead.
- No

fix: Fix deadkey sequences ending with space

---

lua/intro.lua
src/bridge/setup.rs

This emulates the standard Neovim `:intro` message at startup. It's shown if the current buffer is empty and not backed by a file. The message is always centered and does not close when the window is resized, unlike the standard message. Another difference is that this message closes directly on any mode chance except changes from/to cmd mode, while the standard message stays visible if you go into insert mode, until you type something.  
NOTE: That this is not a maintainable solution, so the goal is to get this or something similar implemented in Neovim itself, but for now I think this is good enough for us.
Fixes: https://github.com/neovide/neovide/issues/620
For the corresponding Neovim issue see https://github.com/neovim/neovim/issues/24705
_A breaking change includes anything that …

feat: Show intro message

---

Cargo.lock
Cargo.toml

Just update all the Cargo dependencies using `cargo update`. This, unfortunately leads to a non-working Windows build, since `parity-tokio-ipc` uses `winerror`, but does not add it as a feature itself. So the `winerror` feature of `winapi` is manually set to fix it.
- No

chore: Update cargo dependencies

---

src/bridge/command.rs
src/bridge/mod.rs
src/main.rs

- Fix
Don't rely on the shell specific `exists`, instead run `nvim -v`. Additionally, if there's unexpected output, for example if  your shell is configured wrongly to output something when run in non-interactive mode, it will tell you so, instead of failing with very strange errors later.
The `neovim-bin` argument has also been changed to always require the binary to exist, instead if falling back to `nvim` as that's probably not what the user wants. If `neovim-bin` contains path separators the binary will be tried directly, otherwise `which` will be used to find the correct executable.
The which command has also been changed to always use the which crate first to avoid shell specific issues (for example nushell).
The output is printed directly to stderr instead of the log, for a more …

fix: Improve nvim detection

---

src/renderer/fonts/caching_shaper.rs
src/renderer/fonts/font_options.rs
website/docs/configuration.md

- Feature
Allows for letter spacing by setting the width in guifont
No

add width to guifont settings

---

lua/intro.lua
src/bridge/events.rs
src/bridge/mod.rs
src/bridge/setup.rs
src/bridge/ui_commands.rs
src/editor/mod.rs

`msg_intro` is now used to show the intro message, when it's available. That will happen once this Neovim PR is merged and released https://github.com/neovim/neovim/pull/24764. Otherwise the message text it built manually like before, and showed using `VimEnter`
In addition to this it fixes these two issues
* The `shortmess`+=I` option now works
* The message now closes properly when using `dashboard-nvim`. And most likely in some other situations that did not work previously. The issue was that the lazy loading of `packer.nvim` (and maybe lazy.nvim) with `event=VimEnter` causes `VimEnter`to be called twice.
It also changes the use of lua random to VIM random to avoid polluting the global lua random seed.
_A breaking change includes anything that breaks backwards compatibility either at …

fix: Show intro message when the ui command msg_intro is received

---

src/editor/window.rs

This fixes the problem with some characters disappearing when using Neovim 0.9.2 and greater. See https://github.com/neovim/neovim/issues/25011
Repeats of zero times should be ignored, they are mostly useful for terminal Neovim to distinguish between empty lines and lines ending with spaces.
- No

fix: Fix disappearing characters on Neovim 0.9.2 and greater

---

src/bridge/handler.rs
src/bridge/mod.rs
src/bridge/setup.rs
src/main.rs
src/renderer/mod.rs
src/renderer/opengl.rs
src/renderer/rendered_window.rs
src/window/mod.rs
src/window/window_wrapper.rs

**NOTE: This code targets the `improve-render-loop` branch**
* The window is now created as hidden at startup with the correct size from the start, unless `geometry` is specified. 
* Adds support for `:columns` and `:lines`, to change the geometry at any time, including from `init.vim/lua`
* The resizing during startup happens once at `VimEnter` to make it robust against apparent race conditions like https://github.com/neovide/neovide/issues/1972 and https://github.com/neovide/neovide/issues/1580
* https://github.com/neovide/neovide/issues/1965
* https://github.com/neovide/neovide/issues/1958
* https://github.com/neovide/neovide/issues/181
* https://github.com/neovide/neovide/discussions/1857
* Refactors the code to separate `create_window` and `main_loop`.
TODO: Check for open issues …

fix: Improve windows creation and sizing

---

src/window/keyboard_manager.rs

Added numpad support

---

Cargo.lock
Cargo.toml
src/bridge/ui_commands.rs

- Fixes https://github.com/neovide/neovide/issues/1477
This will use the newly added [nvim_ui_set_focus](https://neovim.io/doc/user/api.html#api-ui) function to notify neovim of focus gained/loss.
- No

Tell neovim focus was gained/lost via 'ui_set_focus'

---

src/window/keyboard_manager.rs
src/window/mouse_manager.rs

**NOTE:** this needs careful testing before merging, so that something else does not break,
This fixes https://github.com/neovide/neovide/issues/2017  - "can't map `<c-s-v>`". This is done by sending shfit when it's combined with CTRL and an ascii alpha character. See the corresponding logic here https://github.com/neovim/neovim/blob/c422722b2e94b94d7f9374dbae12f17580cd1d41/src/nvim/keycodes.c#L764-L799 
It also partially fixes the following issue https://github.com/neovide/neovide/issues/1237 - "CMD + SHIFT works as CMD only". Partially because it's likely not dealing with all the cases. The real issue is in Winit. The fix is to normalize shifted asicii alpha characters already on the Neovide side. This is always done one the Neovim side anyway, so it should be a safe thing to do. 
Note …

fix: Fix some mappings involving shift

---

src/editor/mod.rs
src/editor/window.rs
src/renderer/cursor_renderer/mod.rs
src/renderer/mod.rs

This fixes some clippy warnings caused by rust 1.72.
The DrawComandBatcher is not `send+sync` and not moved between threads so it does not need atomic reference counts.
- No

chore: Fix new clippy warnings from rust 1.72

---

src/bridge/handler.rs
src/bridge/setup.rs
src/window/mod.rs
src/window/window_wrapper.rs
website/docs/commands.md

Adds a command which focuses the Neovide window. This is useful for things like neovim_remote which causes neovim to do some action such as opening a file. Without a feature like this, it is impossible to bring the neovide window to the front as a part of remotely opening a file to edit.
Adds `NeovideFocus` which sends a notification to the bridge. This notification triggers sending a WindowCommand::FocusWindow event which is handled on the WindowWrapper to focus the winit platform window.
Addresses https://github.com/neovide/neovide/issues/1974
Feature
No
Tested by executing `call timer_start(2000, { tid -> execute('NeovideFocus')})` and switching to another window quickly. After a 2 second delay, the neovide window is correctly focused.

Add command to focus the neovide window

---

src/editor/window.rs
src/renderer/mod.rs
src/renderer/rendered_window.rs
src/window/window_wrapper.rs

* Note: builds on top of https://github.com/neovide/neovide/pull/2027, so this should be merged and reviewed after that.
The floating windows are now re-positioned to fit inside the main window, as long as it's possible. And the same thing is done for the messages window, so that you don't see a blank screen if there are errors at startup.
* https://github.com/neovide/neovide/issues/1641 will be fixed once it's completely merged to main.
- No

fix: Reposition the floating windows inside the main window

---

src/bridge/handler.rs
src/bridge/mod.rs
src/bridge/setup.rs
src/cmd_line.rs
src/dimensions.rs
src/editor/mod.rs
src/editor/window.rs
src/main.rs
src/renderer/mod.rs
src/renderer/rendered_window.rs
src/settings/mod.rs
src/settings/window_size.rs
src/window/mod.rs
src/window/window_wrapper.rs
website/docs/command-line-reference.md

* Fixes the window not showing up when there are error messages or `lazy.nvim` is updating for example. This was reported by @9mm here https://github.com/neovide/neovide/pull/2035#issuecomment-1732360990
* The initial size can now be specified by `--grid`, if a size is given then that's used, otherwise the grid will be read from `init.vim/lua`
* The arguments `--size`, `--maximized` and `--grid` are now mutually exclusive
The implementation is a bit hackier than I would want and shows the window when `win_viewport` or `grid_line` is recieved. This is due to the neovim limitations discussed here:
* https://github.com/neovim/neovim/issues/25377
And the main reason for supporting an empty `--grid` argument is because of this:
* https://github.com/neovim/neovim/issues/25378
**NOTE:** Includes …

fix!: window not showing up

---

src/bridge/setup.rs
src/settings/mod.rs

- Fix
- No
I got the error below connecting remote neovim on my machine.
```console
Error detected while processing function NeovideNotifycursor_animation_lengthChanged:
line     1:
E475: Invalid argument: Channel doesn't exist.
```
`g:neovide_channel_id` has 3 in my environment.
But the embedded Vim script always uses 1.
This PR just makes it use `g:neovide_channel_id`.
I don't know how to write the tests.
Please tell me where I should put the tests or merge the PR and add tests in another PR 🙏 
macOS Monterey 12.6.7
```console
> /opt/homebrew/bin/nvim --version
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.0-beta3
system vimrc file: "$VIM/sysinit.vim"
fall-back for $VIM: …
```

Fix config change notification using remote neovim

---

src/bridge/setup.rs

- Fix
- No
The variable `neovide_channel_id` was NOT initialized in some cases.
This PR sets the variable when neovide gets the channel.
It resolves https://github.com/neovide/neovide/issues/2069

set neovide_channel_id always

---

Cargo.toml
src/bridge/command.rs

- Fix #2060
- No
I confirmed this fix on Ubuntu 22.04 and macOS 13.6.

Tokenize command arguments in `$NEOVIM_BIN` (fix #2060)

---

lua/init.lua
src/bridge/setup.rs

Moves the setup code to lua, which makes the code easier to read and it also makes it slightly faster.
**NOTE:** Depends on https://github.com/neovide/neovide/pull/2061 and should be reviewed and merged after that
* No

chore: Move the initial setup to lua

---

src/bridge/ui_commands.rs

I tested this commit by dragging and dropping file named `W:\tmp\neovide\(abc)\example#abc%def.txt` and it was opened successfully.
Fixes #1983
- Fix
- No

fix: run :edit command with nvim_cmd to escape special characters

---

neovide-derive/src/lib.rs
src/window/mouse_manager.rs

Fixes mouse dragging
* https://github.com/neovide/neovide/issues/2080
Mouse move should not be sent when the mouse is dragged. It looks like Neovim can't deal with both events happen simultaneously.
This also fixes a clippy issue.
- No

fix: Fix mouse dragging

---

src/bridge/mod.rs
src/bridge/ui_commands.rs
src/error_handling.rs
src/renderer/fonts/caching_shaper.rs
src/renderer/fonts/font_options.rs

It addresses #2077 by fist implementing a new parallel `UiCommand`, `ShowError { message: String }` which gets translated to neovim's [`echomsg`](https://neovim.io/doc/user/eval.html#%3Aechom), and then using it in tandem with `log::error!` in `CachingShaper::update_font` (when `self.font_loader.get_or_load` fails).
- Yes
- Invalid [`guifont`](https://neovim.io/doc/user/options.html#'guifont') values will now error out instead of silently being accepted. To pick no hinting or aliased edging, you should now use `#h-none` and `#e-alias`, respectively.
- *Actually, just checked the docs, and they already specified those options, even though the code didn't check for them specifically, they were just being handled on the wildcard match. Still this is a breaking change because of the new …

Report error when setting a wrong guifont value

---

.github/workflows/build.yml

Updates the CI images to macOS 12. MacOS 12 - Big Sur is no longer supported according to https://en.wikipedia.org/wiki/MacOS. I don't see anything in the Rust release notes or in the Gitlab CI release notes about macOS 11 being unsupported though.
But in any case this seem to fix the CI problems we have compiling the `aarch64-apple-darwin` image, which broke after this was released https://github.com/actions/runner-images/releases/tag/macOS-11%2F20231030.1 and can be seen here https://github.com/neovide/neovide/actions/runs/6768373367/job/18392914175?pr=2106 for example. This has been verified on my fork https://github.com/fredizzimo/neovide/actions/runs/6773128253/job/18407618899.
This possibly breaks Neovide on macOS 11 and earlier.

chore!: Update the macOS CI to use macOS 12 instead of 11

---

src/main.rs
src/renderer/cursor_renderer/cursor_vfx.rs
src/renderer/cursor_renderer/mod.rs

Fixes https://github.com/neovide/neovide/issues/2001
- Fix
- No

fix: do not spawn particles when jumping to a location instantly

---

Cargo.lock
neovide-derive/Cargo.toml
neovide-derive/src/lib.rs
src/bridge/handler.rs
src/bridge/session.rs
src/main.rs
src/renderer/cursor_renderer/cursor_vfx.rs
src/settings/from_value.rs
src/settings/mod.rs
src/window/keyboard_manager.rs
src/window/mod.rs
src/window/mouse_manager.rs
src/window/settings.rs
src/window/update_loop.rs
src/window/window_wrapper.rs

Tracks the mousemoveevent option so that we dont send mouse move events when we shouldn't.
To do this I updated our settings infrastructure to allow option settings. This is done by adding an `option` attribute to the field that should be backed by an option instead of a global variable. For now all options require a name as they are normally named by neovim and have strange conventions.
While I was in these systems I also added a Changed event which is raised whenever a field on a setting object is updated. This allowed me to remove our current option observation code in favor of tracking updated events.
@fredizzimo to do this I recombined the keyboard settings and window settings structs so that they could both be handled in one location. I believe you introduced that change (maybe) so …

Observe mousemoveevent option

---

src/renderer/mod.rs
src/renderer/rendered_window.rs

Only cast floating window shadows if not contained by a previous floating window
Fixes https://github.com/neovide/neovide/issues/2113
- Fix
- No

Fix stacked floating window shadows

---

src/renderer/grid_renderer.rs
src/renderer/mod.rs
website/docs/configuration.md

Make automatic underline scaling the default and change the existing configuration to be a scale factor as per user request
Implements https://github.com/neovide/neovide/issues/1976
- Feature
- Yes
Removed old underline_automatic_scaling config as it seems to work great and I haven't seen any requests for how to enable it. The scale factor feels like a better user facing config.
The new system also slightly adjusts where the aliasing starts so that its a clamp instead of an arbitrary cutoff

 Add underline scale factor config

---

src/editor/mod.rs
src/renderer/fonts/font_options.rs
src/settings/mod.rs
src/window/renderer.rs

- Other
- No
This just fixes some warnings when compiling on nightly and running cargo clippy. No functionality has been changed.

refactor: fix compilation warnings

---

lua/init.lua
neovide-derive/src/lib.rs
src/bridge/mod.rs
src/bridge/setup.rs
src/settings/mod.rs

The new option observation starts sending notifications earlier than the previous solution. So we need to ignore the columns and lines change notifications until the ui has finished initializing or we don't properly set the window size
- Fix
- No

Fix remember window size

---

src/bridge/command.rs

- Fix
- No
Added a missing CREATE_NO_WINDOW when spawning a new shell command on Windows. Without this flag, a console window would temporarily appear and disappear while starting Neovide. Although it only appeared briefly, it could also steal focus from the Neovide window. I also standardized on just one way to set this flag during process creation, since there were multiple different styles within just a couple of lines of each other.

fix: fix console window not hidden for Windows shell command

---

src/editor/mod.rs

If Neovim attempts to send an empty window title, it is now set to
Neovide instead, rather than the empty string.
This improves two user scenarios:
- Users who utilize assistive technologies will now always observe a
window title by default.
- Users of window managers that rely on window titles will have improved
integration.
The precipitating use case was using Komorebi, a tiling window manager
for Windows. Komorebi uses an empty window title as a strong signal that
the software is a hidden window, as this is a common convention on the
platform.
Updates https://github.com/neovide/neovide/issues/1553

fix: prevent empty window title

---

src/main.rs
src/settings/window_size.rs
src/window/mod.rs
src/window/window_wrapper.rs

- Feature
- No
When neovide starts up, it uses a default grid size unless the grid size has explicitly been provided. This is problematic when relying on neovide to remember the last window size, because the grid size will be out of sync with the physical window size. The UI will initially be rendered at the wrong size, which not only doesn't look great, but exposes some other issues like the noice mini view not handling resizes properly. So if a noice mini view is rendered immediately upon startup, and neovide resizes the grid, the mini view will stay in place until it times out and disappears. In my case it stays in the middle of the screen until the 5 second timeout passes, which is quite annoying.
I thought about playing with not making the window visible until the first resize had …

feat: persist grid size along with window size

---

src/settings/window_size.rs

Use a separate directory for storing application data, i.e. window settings, instead of re-using Neovim's.
- Fix
- See #2132
- Arguably
Existing window settings will be lost when using a neovide version with this change, but that data is arguably somewhat ephemeral in nature, or at least trivial to recreate.

fix: Use own data directory instead of nvim's

---

src/main.rs
src/renderer/opengl.rs
src/renderer/vsync/macos_display_link.rs
src/renderer/vsync/mod.rs
src/renderer/vsync/vsync_macos.rs
src/window/mod.rs
src/window/update_loop.rs
src/window/window_wrapper.rs

Fix #2073, fix #2093 
This pr uses display link api on macos to correctly do vsync. The opengl vsync seems broken on macos.
~BLOCKED by #2097~
UNDER WORKING: Don't merge now. Just to stop from duplicate work.
BREAKING CHANGE: This may totally change the structure of vsync usage.
TODOS:
@fredizzimo I have some questions about vsync usage. In current code, vsync seems owned by the update loop. But as I pointed out before, the display link is specific to a screen. So the structure of vsync usage should be changed as I think. To be simple, I make vsync owned by a window. And when window moves and the screen is changed, vsync updates. Do you have any ideas about this?

feat!: use display link api to implement vsync on macos.

---

Cargo.lock
Cargo.toml
src/window/mod.rs
src/window/update_loop.rs

When the winit vsync is used, the event loop should never be polled, otherwise the CPU usage is just wasted. Winit will send the redraw request and wake the loop up when it's time to render anyway.
All other ways of doing vsync, just blocks inside the loop itself, so polling should be used there.
This also updates the tracy profiler to the latest version.
- No

fix: Don't poll the event loop on Wayland to reduce the power usage

---

src/window/window_wrapper.rs

This changes the order of waiting for vsync and swapping the buffers. This reduces the input latency since reading the inputs and the swap happens during the same vsync interval, rather than different ones.
- No

fix: Change the order of vsync wait and swap buffers to reduce latency

---

src/settings/window_size.rs
src/window/mod.rs
src/window/window_wrapper.rs

Some platforms report a zero window size when minimized, so ignore that when saving the window size and resizing the Neovide grid.
Also enforce a minimum and maximum window size when restoring a saved size. This ensures that a window with a zero size is not displayed.
Fixes
* https://github.com/neovide/neovide/issues/2015
Fixes partially:
* https://github.com/neovide/neovide/issues/2141
It also fixes the annoying issue that the window layout changes when the window is minimized and then restored again.
- Yes, windows sizes less than 300x150 or bigger than 8192x8192 can't be saved.

fix!: Ignore window size when minimized

---

src/window/settings.rs

Fixes issues where ime isn't working on configs without the ime setting explicitly set.
Addresses https://github.com/neovide/neovide/issues/2158

Revert unintentional change to default ime setting

---

lua/intro.lua
src/renderer/rendered_window.rs
src/window/keyboard_manager.rs
src/window/mod.rs
website/docs/maintainer-cookbook.md

Done with `typos --exclude src/bridge/ui_commands.rs -w` and fixing the remaining printed ambiguous ones manually.
`ui_commands.rs` had a false positive in the vim options.
- Codestyle
- No

style: fix typos

---

Cargo.toml
src/bridge/ui_commands.rs
src/editor/mod.rs
src/profiling/profiling_disabled.rs
src/profiling/profiling_enabled.rs
src/renderer/cursor_renderer/mod.rs
src/renderer/mod.rs
src/window/keyboard_manager.rs
src/window/update_loop.rs
src/window/window_wrapper.rs

* Add support for profiling async tasks
* Add support for plotting graphs when profiling
* Add support for named frames (shows the duration of a re-occuring task) with a name
* Add more profiling events that helps especially with viewing the event flow
- No

chore: Improved profiling

---

src/bridge/command.rs
src/cmd_line.rs
src/main.rs
src/settings/config.rs
src/window/keyboard_manager.rs
website/docs/command-line-reference.md

Attempts fixing https://github.com/neovide/neovide/issues/2187  and a temporary solution to https://github.com/neovide/neovide/issues/2147 until a better solution is issued
Fixes https://github.com/neovide/neovide/issues/1987 temporarily
- No

feat: NEOVIDE_FORK environment variable

---

src/bridge/ui_commands.rs
src/window/mouse_manager.rs

Closes #2148 
Implement support for X1 and X2 mouse buttons (commonly known as "back" and "forward")
- Feature
- No

feat: X1 and X2 mouse button support

---

Cargo.lock
Cargo.toml
src/main.rs
src/renderer/vsync/mod.rs
src/renderer/vsync/vsync_macos.rs
src/renderer/vsync/vsync_win.rs
src/window/mod.rs
src/window/update_loop.rs
src/window/window_wrapper.rs

This makes rendering a little bit smoother, at least on some platforms, and also cleans up and unifies some code.
* Remove some redundant polling for new events after the first frame is rendered
* Do the animation and shaping as early as possible in the frame, which leaves just rendering to the end. This makes the rendering part much more predictable, which plays nicer with how some Wayland compositors are made. For example on Gnome many frames were too late because of the unpredictability. 
* Got rid of the manual dt calculation, and tries to use the monitor refresh rate instead, with a fallback to `neovide_refresh_rate`. 
* The frames are generated using a real-time clock and the frame rate calculated above, duplicating frames when rendering too fast. But that duplication does not …

feat: Smoother render loop

---

lua/init.lua
src/bridge/events.rs
src/bridge/mod.rs
src/editor/mod.rs
src/editor/style.rs
src/renderer/cursor_renderer/mod.rs
src/renderer/rendered_window.rs
src/window/settings.rs
website/docs/configuration.md

This fixes the scrolling of windows with winbar or native borders by only scrolling the inner region. 
The solution is quite hacky, see the new `neovide_unlink_border_highlights` option for example. But I think this is the best we can do with the current version of Neovim.
I also changed `Arc<Mutex<Line>>`  `<RC<RefCell<Line>>` because it's never accessed concurrently.
* Fixes https://github.com/neovide/neovide/issues/1550
* Fixes https://github.com/neovide/neovide/issues/1446
**NOTE:** This probably needs a bit more testing before merging.
- No

fix: Scrolling of windows with winbar or native borders

---

src/renderer/rendered_window.rs

The scroll animation was previously always reset when the window position changed, because the same command was used for positioning and resizing of the windows. This is now changed so that the scroll animation is kept for position or width changes, and only reset when the height changes.
This also add a tracy profiler graph of the scroll position.
* Fixes https://github.com/neovide/neovide/issues/2203
- No

fix(scrolling): don't reset the scrolling when the window position changes

---

src/window/window_wrapper.rs

The change to use wayland frame callbacks caused a regression where it's possible to receive new winit events between the render request and the actual render, and during that the window size might change, so ensure that we always handle these events and resize the buffers.
* Fixes #2200 
- No

fix: ensure that the opengl buffers are resized after a resize or scale change

---

src/renderer/rendered_window.rs

@falcucci noticed that https://github.com/neovide/neovide/pull/2208 for him re-introduced the problem with text being hidden randomly. I couldn't reproduce this myself, but apparently this patch works for him.
- Fix
- Regression as introduced by https://github.com/neovide/neovide/pull/2208
- No

fix: don't hide random text

---

src/bridge/ui_commands.rs

fix: #2233 by replacing echo command with api call

---

src/renderer/rendered_window.rs

Fixes https://github.com/neovide/neovide/issues/2234 as per suggestion by [fredizzimo](https://github.com/fredizzimo).
- Fix
- No

fix: #2234 by adding !self.scrollback_lines.is_empty() check

---

src/editor/mod.rs

Neovim sometimes requests that a grid be anchored to itself when using the context menu. This PR addresses this by catching the recursive case in the editor and logging a warning.
Fixes https://github.com/neovide/neovide/issues/2175
- Fix
- No

Fix issue with recursive floating window anchors

---

src/renderer/fonts/caching_shaper.rs

A font with zero width or height, will cause the grid to become zero sized, which causes a lot of problems, including division by zero. This fix prevents that from happening.
fix https://github.com/neovide/neovide/issues/2221
- No

fix: Prevent the font from becoming zero sized

---

src/renderer/fonts/caching_shaper.rs

The old `font_info` was used after the new font size had been calculated using the fudge factor. In practice I never saw problems due to this, since the grid sizes were also rounded the same way. But it was still incorrect, and there could very well be some font sizes that were rendered wrong, with either one pixel to wide or narrow grid size.
- No

fix: Reset the cached font info after the fudge factor is updated

---

lua/init.lua
src/bridge/handler.rs

Send the quit request using rpc requests instead of notify, so that Neovim waits until Neovide has processed the possible return value until it quits.
Sometimes, without this wait the return code is never received by Neovide before Neovim has quit and it's too late, so the wrong return code is returned.
NOTE: To quit with a return code use [:quit](https://neovim.io/doc/user/quickfix.html#%3Acquit)
- No

fix: Use rpc request instead of notify for quit requests

---

Cargo.toml
src/cmd_line.rs

- Feature
- No
----------
Today i was building neovide, and instead of `cargo r -- --help`, i typed `cargo r --help`. And cargo help is colored!
I immediately wanted to have the same colored help in neovide. So, i added it!
They're using `cyan` for command names, and i've used defaults from clap docs, because in our case cyan looks not so fitting.
Take a look!
-------
One thing to be aware of - i expected `Cargo.lock` to be updated, after changing `Cargo.toml`, but it was not updated. Is there something else i need to do to update it?

feat: Add colored output to `--help`

---

lua/init.lua

Updates option reporting to send the initial values of options as well as when they are changed.
This manually excludes lines and columns as they are set dynamically on startup and our logic requires that we set them ourselves before receiving any changes.
fixes https://github.com/neovide/neovide/issues/2222
fixes https://github.com/neovide/neovide/issues/2300
- Fix
- No

Send options on startup as well as on changed except for columns and rows

---

src/bridge/mod.rs

- Fix
- No
This is basically #2130 again. I wanted a cleaner fix, but a lot of the async and threading stuff will need to be reworked. In the mean time there have been enough reports of hangs to justify a quick fix so it's usable.
I tried a couple of things that worked for me before, but an added complication now is the task spawning in `start_ui_command_handler`. If those are stuck in a `recv()`, they just won't exit.
I'm thinking instead of `RUNNING_TRACKER` we need to use cancellation tokens or something tokio can select on so we can break out of futures that will never return. Checking `RUNNING_TRACKER.is_running()` does nothing when stuck in an await, and we shouldn't rely on channels dropping at the end of a scope to break out of these loops, because that drop can possibly not …

fix: fix hang on neovim exit

---

src/window/keyboard_manager.rs

- Fix. Some numpad keys are not mapped to the correct neovim key. With this patch, neovide honors numlock for [`NumpadDecimal`], and sets the correct neovim keycode for [`NumpadComma`] and [`NumpadEqual`].
- No. 
[`NumpadComma`]: https://docs.rs/winit/0.29.10/winit/keyboard/enum.KeyCode.html#variant.NumpadComma
[`NumpadDecimal`]: https://docs.rs/winit/0.29.10/winit/keyboard/enum.KeyCode.html#variant.NumpadDecimal
[`NumpadEqual`]: https://docs.rs/winit/0.29.10/winit/keyboard/enum.KeyCode.html#variant.NumpadEqual
This is a follow up of #2032
See also [neovim docs][0].
Please note that I don't have a numpad with `<kEqual>` and `<kComma>` keys, I could only test kPoint (which is currently …

fix: Handle some more numpad keys

---

src/settings/config.rs
website/docs/config-file.md

- add a new field `title_hidden` to the `config` struct
- set the `neovide_title_hidden` environment variable based on the value of `title_hidden`
- Fix
- No
fixes #2342

feat: add support for hiding window title from config file

---

Cargo.lock
Cargo.toml
src/renderer/fonts/caching_shaper.rs
src/renderer/fonts/font_loader.rs

Updates the `lru` package from 0.7.5 to 0.12.2. 
The old package caused an old `hasbrown` version to be used, which in turn caused an old version of `ahash` to be used, which does not build on the current nightly version of the rust toolchain.
- No

chore: update lru crate to fix building with the nightly toolchain

---

src/window/mod.rs

Fix #2303 
According to winit docs at https://docs.rs/winit/latest/winit/window/struct.WindowBuilder.html#method.with_position, `with_position` sets the position of top left corner of **content** rect instead of **window** rect on macOS, so a `set_outer_position` call is needed.

fix: bug of restoring window position on macos.

---

src/renderer/fonts/font_loader.rs

* fixes https://github.com/neovide/neovide/issues/2352
Only the lower 16 bits of the index returned by Skia are part of the actual font index that should be loaded.
- No

fix: loading of fonts with OpenType font variations

---

Cargo.lock
Cargo.toml
src/bridge/mod.rs
src/bridge/session.rs
src/bridge/ui_commands.rs

- Codestyle
- Other
- No
Updated `nvim-rs` to the latest release. I noticed you're wrapping the `Neovim` instance in `Arc`. That's not really necessary, since `nvim-rs` does `Arc`-wrapping for all components anyways.
There might be performance implications - this removes an indirection, but cloning the `Neovim` instance now needs to bump 3 counters instead of one. My assumption would be that this is a win, but there aren't any benchmarks in place to decide this.Your choice :)

Update nvim-rs, remove superflous arc-wrapping

---

website/docs/troubleshooting.md

Add documentation of instructions of profiling neovide with tracy.
This is the first time I write docs for public. Please point out any spelling or grammar mistakes or inappropriate voice, etc.

doc: instructions of profiling with tracy.

---

website/docs/configuration.md

After my previous PR has been merged and the docs updated I noticed that I accidentally sliced into the documentation of `g:neovide_transparency`, cutting between the description and a screenshot. This PR fixes it. 😅
- Fix
- No

docs: fix show_border cutting into transparent

---

Cargo.toml
src/window/macos.rs
src/window/mod.rs

- Feature
- No
This PR adds Window menu so the app feels more native and adds some potentially useful items, like tiling.
Also make cmd+m shortcut work.
I'm not very sure about the event loop part, open to suggestions.

feat: add window menu on mac

---

Cargo.lock
Cargo.toml
src/renderer/vsync/macos_display_link.rs

This PR removes legacy objc and cocoa dependencies. I'm not 100% sure memory management is correct here and how to test this.
- Refactor
- No

chore: remove legacy objc and cocoa

---

src/bridge/ui_commands.rs

- dropped event now supports multiple paths including folders only;
- change file opening behavior from `edit` to `tabnew` in parallelcommand::filedrop;
- Feature
- No

feat: drop multiple files and folders

---

Cargo.lock
Cargo.toml
src/cmd_line.rs

Three things in life are inevitable: death, taxes, and dependency upgrades.
All crates with breaking version bumps had all of their usages carefully referenced against relevant change logs to ensure no unexpected (documented) changes in behavior were introduced.  
Some of the removed deps are still in the crate graph, but are not direct dependencies, and the additional constraints on their versions does not appear to achieve anything useful.
I refrained from touching some crates like `skia-safe` and dependencies specific to non-linux platforms
- Other
- No (correct me if I'm wrong on this one, not sure if you consider major dependency upgrades breaking for an application)

chore: Upgrade dependencies and remove unused

---

Cargo.lock
Cargo.toml

These features relate to glyph rasterization. They are unused since Neovide uses Skia for text rendering. This removes several dependencies.
- Other
- No

chore: remove swash's scale and render features

---

Cargo.lock
Cargo.toml
src/cmd_line.rs
src/profiling/d3d.rs
src/profiling/mod.rs
src/renderer/d3d.rs
src/renderer/mod.rs
src/renderer/vsync/mod.rs
src/renderer/vsync/vsync_win_swap_chain.rs

This switches to a Direct3D based renderer and finally makes the Windows render loop smooth with almost no frame drops, at least on my machine. 
Using Direct3D will also improve the compatibility with older hardware.
NOTE:
* You can still use the old opengl based rendering by passing the  `--opengl` option. 
* The `--no-vsync` option does not work properly at the moment
* There might be bugs when the device is lost/computer sleeps/monitor turned off
* The device selection code is somewhat naive
* The code probably needs some cleanup, and that's the biggest reason for the draft status. I will probably split this PR into two, one pure refactoring, and another one that adds the functionality.
* This also seem to reduce the stuttering in some Wayland compositors like Mutter/Gnome at the cost …

Direct3D Rendering on Windows

---

src/bridge/api_info.rs
src/bridge/events.rs
src/bridge/mod.rs
src/bridge/setup.rs
src/bridge/ui_commands.rs
src/editor/mod.rs
src/editor/window.rs
src/renderer/cursor_renderer/mod.rs
src/renderer/rendered_window.rs

Implements the neovide side of https://github.com/neovim/neovim/issues/23610 which introduces a new viewport_margins event which tells us what part of the rendered window should actually be scrolled without resorting to inspecting highlight links.
Fully fixes https://github.com/neovide/neovide/issues/2291
Fixes https://github.com/neovide/neovide/issues/2406
Also pulls in apimetadata parsing from https://github.com/neovide/neovide/pull/2438 so that we can disable the hlstate_external extension when we don't need it for performance reasons.
- Fix
- No. Leaves the existing heuristics for inferring the border intact when the new api not available.

Handle new viewport margins event

---

src/bridge/mod.rs

Fix launching neovide with a "fake" neovim instance `neovide --neovim-bin nvim.dev.local`:
nvim.dev.local:
```bash
#!/bin/bash
ssh dev.local "bash -l -c \"nvim $@\"" 
```
- Fix
- No

fix: set startup directory failed is not an error

---

lua/intro.lua
src/bridge/api_info.rs
src/bridge/events.rs
src/bridge/mod.rs
src/bridge/setup.rs
src/bridge/ui_commands.rs
src/editor/mod.rs
src/window/mod.rs
src/window/window_wrapper.rs

Once 0.10.0 is released, we can come back in and remove the intro message stuff altogether, but for now this will prevent the doubled up messages which look funny in current nightly.
- Fix
- No

Prevent intro message hack from showing when the intro message is fixed upstream

---

src/window/update_loop.rs

This fixes a bug where Neovide stops responding for some time after the computer has gone to sleep or disconnected from a remote desktop.
There are actually two different fixes:
1. Properly prepare the frame before respecting OS or Winit initiated rendering requests. This fixes the main bug at least when disconnecting from the remote desktop on Windows. 
2. Don't simulate for more than 1 second. I don't know how to trigger this in practice, but I suspect it can happen if the computer goes to sleep while Neovide is animating. I tested this by disabling fix 1.
NOTE: Marked as draft since it depends on and should be reviewed and merged after that
* https://github.com/neovide/neovide/pull/2470
- No

fix: Temporary hang after sleep

---

src/renderer/grid_renderer.rs

This fixes https://github.com/neovide/neovide/issues/2275 by letting [box drawing](https://en.wikipedia.org/wiki/Box-drawing_characters), [block elements](https://en.wikipedia.org/wiki/Block_Elements), [geometric shapes](https://en.wikipedia.org/wiki/Geometric_Shapes_(Unicode_block)) as well as the [Nerdfont Powerline](https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points#powerline-symbols) (+[Extras](https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points#powerline-extra-symbols)) inherit the background opacity instead.
- (Fix?)
- Feature
- No
| Main | This PR |
| --- | --- |
| ![image](https://github.com/neovide/neovide/assets/19289296/a40300b0-27b7-4 …

feat: draw block characters with background opacity

---

Cargo.lock
Cargo.toml
src/bridge/mod.rs
src/dimensions.rs
src/main.rs
src/renderer/animation_utils.rs
src/renderer/cursor_renderer/cursor_vfx.rs
src/renderer/cursor_renderer/mod.rs
src/renderer/fonts/caching_shaper.rs
src/renderer/grid_renderer.rs
src/renderer/mod.rs
src/renderer/rendered_window.rs
src/settings/mod.rs
src/settings/window_size.rs
src/units.rs
src/window/mod.rs
src/window/mouse_manager.rs
src/window/window_wrapper.rs

This is a big refactor that adds typesafe units almost everywhere, using the [euclid](https://docs.rs/euclid/latest/euclid/) library. The code has also been simplified in a lot of places by using primitives provided by euclid instead of individual points.
Furthermore, many of the type casts have been replaced by safer alternatives, like like `try_into().unwrap()`, crashing instead of doing something completely unexpected. In some places where invalid values are more expected, clamping is used instead.
Most calculations are also done using either floating point or signed numbers, which reduces the need for type casts, so a lot of those could be deleted.
This is a lot of changes, but the code is much easier to read and understand IMO now. It's also safer, since you usually get a compilation …

chore: Use typesafe pixel and grid units

---

src/editor/draw_command_batcher.rs
src/editor/mod.rs
src/editor/window.rs
src/renderer/mod.rs
src/renderer/vsync/vsync_win_swap_chain.rs

According to neovim folks, they can and do send redraw events in any order so long as its in the same batch. This PR addresses our first issue to come of that by manually sorting the batches so that our position WindowDrawCommands always happen before all others.
Fixes https://github.com/neovide/neovide/issues/2464
- Fix
- No

Address viewport margin regression by sorting DrawCommand batches

---

Cargo.lock
Cargo.toml
src/windows_utils.rs

The right click menu register functions are refactored with `windows` and `windows-registry` crates. The refactored code seems simpler and easier to be read and maintained.
- Refactor
- No

Refactor the registry-relevant functions.

---

src/renderer/mod.rs
src/renderer/rendered_layer.rs
src/renderer/rendered_window.rs

This fixes the cacluation of the inner region clipping rectangle, which caused this regression.
* https://github.com/neovide/neovide/pull/2467#issuecomment-2067342150
It also reduces the range of the scrollable lines iterator, which previously did not take border into account. That's not really a problem in practice, since we always need to iterate one more line than the actual grid size anyway, and the clipping rect will take care of clipping it correctly. But it could enable transparency modes when no transparent lines are visible for example.
The `floating_order` field was removed again, since it's unused and causing clippy warnings.
The `sort_order` field was also unused and removed
- No

fix: clipping rect regression

---

src/window/mouse_manager.rs

Previously it was only checked when the mouse moved, but that does not work when new windows are created without moving the mouse.
So, this is fixed by re-checking he window when clicking or scrolling.
* fix https://github.com/neovide/neovide/issues/2175
- No

fix: Determine the window under the mouse on the fly

---

Cargo.lock
Cargo.toml
src/bridge/command.rs
src/profiling/d3d.rs
src/profiling/profiling_enabled.rs
src/renderer/d3d.rs
src/renderer/fonts/caching_shaper.rs
src/renderer/fonts/font_loader.rs
src/renderer/opengl.rs
src/renderer/vsync/vsync_win_dwm.rs
src/renderer/vsync/vsync_win_swap_chain.rs

Briefly complete migrating from `winapi` to `windows`. Known issue: Program will not show a window and closed immediately when building with `profiling` and `gpu_profiling` features enabled. On the other hand, you can still use the program when building without any features enabled. This issue will be fixed in the next commit(s).
- Refactor
- No

Migrate dependency from `winapi` to `windows`.

---

src/window/mouse_manager.rs

* Fixes a regression caused by https://github.com/neovide/neovide/pull/2311. The absolute position of the mouse was returned instead of the relative one.
* A small refactor to the mouse manager, pass a struct instead of individual parameters
* Fixes https://github.com/neovide/neovide/issues/2503
- No

fix: Cursor offset

---

src/main.rs
src/settings/window_size.rs
src/window/mod.rs

- Fix
- No
We're currently saving the grid size for non-maximized windows only. This PR also saves it for maximized windows, because it has the same benefit as for non-maximized windows.

fix: save grid size for maximized windows

---

src/renderer/rendered_layer.rs

- Fix
- No
Floating layer rendering rendered the floating shadow even if disabled in settings. This PR checks the setting before rendering the shadow.

fix: respect floating shadow setting in layer rendering

---

src/cmd_line.rs
src/main.rs
website/docs/command-line-reference.md

Based on discussion here, we should change the defaults to not fork, so this is done here.
* https://github.com/neovide/neovide/issues/2147
Additionally, this prevents any attempts to fork when a terminal isn't attached, since that would have no effect.
- Yes, this changes the defaults, previously Neovide always forked.

fix:! Don't fork by default

---

src/renderer/rendered_layer.rs

- Fix
- No
This is an attempt to make it less likely that floating windows with consecutive z-indexes are rendered together if they shouldn't be rendered together, like the first screenshot in #2502.
Instead of checking if the window rects intersect, I check if one is contained in the other. This isn't foolproof, because we could still have windows with consecutive indexes that should not be rendered together (like the first screenshot in #2502, but in a bigger directory), so the whole window grouping thing needs a lot more thought, and should probably be able to be disabled entirely by an option.
Still, I can't think of any time it would make sense to render two windows with consecutive z-indexes together if one isn't fully contained in the other.

fix: don't group floating windows unless one is fully contained in the other

---

src/bridge/mod.rs
src/bridge/session.rs
src/bridge/ui_commands.rs
src/channel_utils.rs
src/renderer/opengl.rs
src/running_tracker.rs
src/window/mod.rs
src/window/window_wrapper.rs

The main loop now waits for Neovim to quit before exiting. This allows error messages to be shown and dealt with, instead of leaking nvim processes, as neovide will block here https://github.com/neovim/neovim/blob/15a2dd9e963784123273ec830e82e24ecea4ad0b/src/nvim/main.c#L802-L807
It primarily waits for the stdio stream to finish, but due to bugs, like https://github.com/neovim/neovim/issues/26743, that does not always happen, so it additionally waits for the process to exit, and forces a quite if the io stream has not finished within 2 seconds after that. **If you use Neovim nightly with https://github.com/neovim/neovim/pull/28157, it should not happen**
An exit crash that happens on some Wayland systems has also been fixed, by properly shutting down the rendering system before the event …

fix!: Perform a clean exit again

---

src/cmd_line.rs

This adds quotes around the wsl paths passed to Neovim, to deal with spaces and special characters. Relative paths are also converted to absolute before passed to `windows_to_wsl`, so they also work correctly now.
* Fixes https://github.com/neovide/neovide/issues/2506
@Holzhaus, maybe these are something you want to add to your library?
- No

fix: relative WSL paths and paths with spaces

---

Cargo.toml
src/renderer/d3d.rs
src/window/mod.rs

In order to render transparent window backgrounds on Windows with D3D, the drawing is now done using Window's composition engine, see https://learn.microsoft.com/en-us/archive/msdn-magazine/2014/june/windows-with-c-high-performance-window-layering-using-the-windows-composition-engine. This also fixes, the alt-enter hijacking, since the swapchain is no longer bound to the Window. 
Additionally, this PR disables the D3D debug layer by default, since it's not supported on some systems without additional software.
* Fixes https://github.com/neovide/neovide/issues/2517
* Fixes partially https://github.com/neovide/neovide/issues/2465
* Fixes https://github.com/neovide/neovide/issues/2522
- …

fix: Use composition to fix window transparency when using D3D

---

src/renderer/fonts/font_options.rs
src/settings/font.rs

* The `width` and `size` arguments in the font config are now read as points, like `guifont` and almost any other software.
Yes, users that have adjusted their size in pixels will now see too big fonts.

fix!: Use points instead of pixels for the config file

---

src/utils/mod.rs

Add cfg to is_tty so that it isn't built on windows

---

src/renderer/d3d.rs

- Fix
Fixes a crash when minimizing the neovide window when using d3d renderer
- No

Dont resize the d3d buffers if the window size is zero

---

website/docs/configuration.md

The sample Vimscript autocmds for setting `neovide_input_ime` are reversed on the `Cmdline` events, compared to the `Insert` events, and the Lua sample.
- Documentation (fix)
- No

docs: Fix reversed autocmds for setting input_ime

---

Cargo.lock
Cargo.toml
src/renderer/d3d.rs
src/renderer/fonts/font_options.rs
src/renderer/mod.rs
src/renderer/rendered_window.rs
src/settings/config.rs
src/window/window_wrapper.rs
website/docs/configuration.md

* Full font hinting is now the default again. None was causing some quality issues, especially with some font sizes. Note that full hinting can cause some font distortion, but that can mostly be avoided by using font sizes that are exact pixels. Here are some examples with a scale factor of 100% : 8.25, 9, 9.75, 10.5, 11.25, 12, 12.75
* Loading of the config file uses debouncing to make it much more reliable. Before this it sometimes failed to detect new settings, and sometimes read partial files. At least on Linux.
* The edging and hinting now takes effect immediately when changing them from the config file
* Contrast and Gamma is enabled for D3D, which was forgotten in the original PR.
- No

fix: Some more font fixes

---

src/renderer/fonts/caching_shaper.rs
src/renderer/grid_renderer.rs

- Fix
Figured fixing #2561 would be fairly straightforward, so I took a stab at it. The core issue was the sign flip in `src/renderer/grid_renderer.rs:167` - `self.shaper.underline_position()` returns a negative number so subtracting it from the final underline position was offsetting the underline in the wrong direction. From what I can tell, the reason why it wasn't causing an issue before 6b04db543f68d03a1cd6e1ad4b3370732f9e1a0a was because `self.shaper.underline_position()` was usually just returning zero due to lost precision from all the float -> int conversions everywhere.
I also had to tweak the positioning of the other underline types, since those were based off of the previous incorrect positioning. I enabled anti-aliasing for all underline types because without it the bottom …

fix: Fix underline rendering

---

src/main.rs
src/renderer/d3d.rs
src/renderer/fonts/caching_shaper.rs
src/renderer/fonts/font_loader.rs
src/renderer/mod.rs
src/renderer/opengl.rs
src/settings/window_size.rs
src/window/error_window.rs
src/window/keyboard_manager.rs
src/window/macos.rs
src/window/mod.rs
src/window/mouse_manager.rs
src/window/update_loop.rs
src/window/window_wrapper.rs

Instead of creating a hidden window and then potentially resize and show it, we now create the windows inside the event loop with the correct size on demand. 
This fixes a few macOS issues, and also some flickering and bad animation when the window is created. It also probably fixes some issues with tiling window managers
* Fixes https://github.com/neovide/neovide/issues/2142
* Fixes https://github.com/neovide/neovide/issues/2554
* Fixes https://github.com/neovide/neovide/issues/2330
* Fixes https://github.com/neovide/neovide/issues/2087
* Fixes https://github.com/neovide/neovide/issues/1888
* Fixes https://github.com/neovide/neovide/issues/1806
* Fixes https://github.com/neovide/neovide/issues/1783
* Fixes https://github.com/neovide/neovide/issues/915
- No

fix: Delay the window creation until it's time to draw

---

src/window/window_wrapper.rs

With the recent commit neovide_scale_factor got broken. This change will resolve the issue. 
Thanks @fredizzimo 
Issue:
left is compiled from source now and right is neovide 0.13 version.

neovide_scale_factor minor fix

---

src/renderer/d3d.rs

For some reason it appears like dxgi 1.4 is unavailable on some Windows 10 and Windows 11 machines. I have no idea why, since it should be bundled with Windows since the very first 10 release.
This relaxes those requirements, and also don't pass `DXGI_CREATE_FACTORY_DEBUG`, since that's another failure point.
* fixes https://github.com/neovide/neovide/issues/2556
- No

fix: Require only DXGI 1.2 when not debugging

---

src/settings/config.rs
website/docs/config-file.md

Not all of the available settings are currently listed, as documentation suggests.
* Fork: important, as recent release changed the default behaviour and command line option is worded differently; had to dive into the code to find it.
* Theme: another recently added option.
* Font: provided a (default) example to better explain the expected format.
- Documentation 
- No

docs: Update list of currently available settings

---

src/renderer/rendered_layer.rs

fix: group floating window

---

src/utils/test.rs

refactor: remove unnecessary casting to `usize`

---

src/bridge/command.rs

If we assume that having `$TERM` set means the user is in an interactive terminal session, we can simply run the nvim command directly instead of wrapping it in `/usr/bin/login`, preserving their environment variables. Testing locally, this does work: the simple `PATH="/foobar:$PATH" neovide` test I used in the bug report works again.
Note that this is different from the [pre-0.13 behaviour](https://github.com/neovide/neovide/blob/71e9fa49fcb393662ee03e42968724b91cde8e62/src/bridge/command.rs#L192-L194), which would still spawn a shell but just not provide `-l`. This just executes `nvim` directly. That's what I think @fredizzimo is suggesting in [this comment](https://github.com/neovide/neovide/issues/2584#issuecomment-2125654862), but I don't know if spawning a shell has effects other …

fix: Don't use login shell on macOS if `$TERM` is set

---

src/window/window_wrapper.rs

The previous attempt of this fix was in:
* https://github.com/neovide/neovide/pull/2571
But it turned out that, the fix caused fcitx to crash all the time, so this fixes it in the correct way, I hope.
NOTE: When I first made this fix, it seemed like it was stil possible to make it go into the wrong state if it was enabled without moving the cursor. But after that I have attempted to repeat it 10s of times without luck, so it's either very random, when it did happen, maybe every other try, and then basically never. Or more likely, fcitx was in some bad state due to my earlier attempts, and therefore caused the problems.
If this happens however, it would be good to capture a log with `WAYLAND_DEBUG=1 neovide`. If there is a problem, then it's probably because of some race condition when …

fix: Another attempt to fix the IME not geting properly enabled

---

src/cmd_line.rs

fix #2605: indicate that `--no-fork` is now the default behavior

---

src/renderer/fonts/caching_shaper.rs

Fixes neovide/neovide#2600
- Fix
- No

fix: Position underline correctly with linespace >0

---

src/renderer/mod.rs
src/renderer/rendered_window.rs

* Remove the error log for WindowCommand sent to uninitialized grid when multigrid is disabled. 
* Fixes https://github.com/neovide/neovide/issues/2576
* Remove unnecessary `prepare_lines` message 
- No

fix: Remove some logspam

---

Cargo.toml
src/error_handling.rs
src/main.rs
src/window/settings.rs
src/windows_utils.rs

1. Fixes crash when the GUI error message window is shown and the command line parsing fails.
2. Fixes yanking from the GUI error message window, when it's shown before the clipboard has been initialized
3. The errors/messages are always printed to stdout/stdout when they originate from the command line parsing. After that they are either shown in the console or the GUI window depending on if a TTY is attached or not. 
* Fixes https://github.com/neovide/neovide/issues/2572
* Fixes https://github.com/neovide/neovide/issues/2204
- No

fix: Neovide --version and Neovide --help

---

src/main.rs
website/docs/editing-with-external-tools.md
website/docs/troubleshooting.md

I noticed that my neovide call looks like this in the process list:
```
> ps ax | grep -E '[n]eovide'
134800 pts/2    Sl     0:00 /usr/bin/neovide --no-fork --fork
```
I'm using `--fork` argument, why there's --no-fork?
@fredizzimo probably you forgot to remove this?
I removed this arg, and it works as expected. Also, cleaned up docs.
- Fix
- No

chore: Remove obsolete `--no-fork` arguments

---

src/bridge/events.rs
src/editor/mod.rs
src/renderer/mod.rs
src/renderer/rendered_layer.rs
src/renderer/rendered_window.rs

The layer groups are now drawing using the same order and blending as the terminal mode Neovim. There's no blending between the windows, a window on the top (inside the same group), always overwrites the window below it. This makes the sort ordering important, but the UI protocol does not provide us all the information directly, so it has been reverse engineered from the Neovim source code. And the order is the following:
1. Z-index
2. Creation order, actually the first call to `win_float_pos` for a window. This order is reset when the window is hidden.
Furthermore, each time a `grid_cursor_goto` event is received, that window is moved to the top in its z-index.
The `neovide_experimental_layer_grouping` option has also been fixed. It didn't work as intended before. Even if this current …

fix: emulate Neovim layer drawing

---

.github/workflows/build.yml
src/utils/mod.rs
src/utils/test.rs

* Reviewdog stopped working from because of a Github runner update. Additionally, the output was quite confusing, so this replaces it by a standard job running `clippy`. With a proper failure when there are errors.
Note, due to https://github.com/actions/runner/issues/2347, all errors from the nightly build are ignored. It would be preferable to just generate a warning instead of a failure, but the Github actions do not support that. We also don't want to fail pull requests due to new Clippy warnings included in the nightly toolchain (which might even be false positives due to the unstable toolchain). My plan is to introduce a nightly build at some point, which actually fails the Clippy step, so that the maintainers can fix the Clippy warnings, before the next stable Rust release.  
* …

Run Clippy directly instead of reviewdog

---

src/window/keyboard_manager.rs

Fixes https://github.com/neovide/neovide/issues/2669
- Fix
- No
I had this keymap that wasn’t working before the change and works with it
```
vim.keymap.set('n', '<C-Space>', '<cmd>echomsg "Test!"<CR>')
```

fix: C-Space was not mappable on Windows

---

src/bridge/exit_handler.lua
src/bridge/ui_commands.rs
website/docs/configuration.md

This adds functionality to detach the Neovide instance from a remote Neovim instance without fully closing Neovim. Functionality can be configured by the user, which is detailed in the documentation changes.
Comments and suggestions are always welcome, especially in regards to which option should be default.
- Feature
- No

Detach prompt

---

website/docs/installation.md

Removes Snap store install option from the website (at least until the snap version stops being broken)
See #1149
- No

Remove Snap store from installation.md

---

src/window/window_wrapper.rs

The full screen state and `input_macos_option_key_is_meta` are now properly set when the window is created.
* fixes https://github.com/neovide/neovide/issues/2608
* fixes https://github.com/neovide/neovide/issues/2637
- No

fix: Ensure windows settings are initialized when the window is created

---

src/renderer/cursor_renderer/mod.rs
src/renderer/fonts/caching_shaper.rs
src/renderer/grid_renderer.rs

* Rename `y_adjustment` to `baseline_offset`
* The `leading/linegap` is now distributed equally on top and bottom, like for the `linespace` setting
* The underline offset is relative to the `baseline_offset`
- No

fix: A smal tweak to how the baseline offset and underline position is calculated

---

lua/init.lua
src/bridge/clipboard.rs
src/bridge/handler.rs
src/clipboard.rs
src/window/error_window.rs

* The clipboard provider is now properly reloaded after setting up the clipboard. 
* This also adds support for the selection register `*` on Linux
* Fixes https://github.com/neovide/neovide/issues/2613
- No

fix: Fix the remote clipboard support

---

src/main.rs

Unset `ARGV0` to fix AppImage
* fixes https://github.com/neovide/neovide/issues/2477
- No

fix: Unset ARGV0 to fix AppImage launch

---

Cargo.lock
Cargo.toml
src/renderer/fonts/caching_shaper.rs
src/renderer/fonts/font_options.rs
src/renderer/grid_renderer.rs
src/renderer/mod.rs
src/window/window_wrapper.rs

Load and use the fonts from the config instead of hardcoded ones
- Yes, the linespacing is now multiplied by the scale factor as it should be.

fix(wgpu)!: Load and use the fonts from the config instead of hardcoded ones

---

Cargo.lock
Cargo.toml
src/renderer/fonts/caching_shaper.rs
src/renderer/grid_renderer.rs
src/renderer/rendered_window.rs

Optimize the wgpu text rendering performance by storing the glyph runs, almost like we did with the Skia pictures. That way the shaping only happens when the line changes, and not during each frame rendered.
NOTE: The transparency is still not handled properly, that will be fixed in some later PR.
- No

optimize(wgpu): save glyph runs

---

src/bridge/mod.rs
src/main.rs

* fixes https://github.com/neovide/neovide/issues/2182 (but probably not completely)
Neovim through libuv spawns child processes that inherits all the handles. This means that the stdio and stderr handles are not properly closed, so the nvim-rs read will hang forever, waiting for more data to read. To deal with that the Tokio runtime is forced to shutdown after a timeout.
The timeout for waiting for the streams to close has also been reduced to avoid having a too long shutdown delay.
Also see these libuv issues:
* https://github.com/libuv/libuv/pull/3856
* https://github.com/libuv/libuv/issues/1490
- No

fix: Force Neovide to exit, even if the IO streams are not closed

---

Cargo.lock
Cargo.toml
src/renderer/opengl.rs
src/renderer/vsync/macos_display_link.rs
src/renderer/vsync/mod.rs
src/renderer/vsync/vsync_macos_display_link.rs
src/window/macos.rs
src/window/mod.rs
src/window/update_loop.rs
src/window/window_wrapper.rs

This pr does following 2 major things:
- Upgrade `objc2` and remove `icrate`, since `icrate` is deprecated and migrated to `objc2-*`. Related structs and  functions are updated to the new ones.
- Try to move as much as possible macOS specific code into `macos.rs`.
- Menu creation.
- File handler.
MacOS part improvement
- Rename `vsync_macos` -> `vsync_macos_display_link`. So we can create another one like Metal vsync on macOS, just like how it is done on Windows.
- Getting `NSWindow` from winit `Window` logic is extracted out into a function, because it is used both in `macos.rs` and `macos_display_link.rs`.
- Main thread related improvement
- Improve `MainThreadMarker` creation. It is now only created and checked after entering macOS-specific code from common codes, instead of being …

chore: update objc2 and remove icrate. also some refactor.

---

src/window/macos.rs
src/window/mod.rs

fix #2776
The problem is caused by registering `NSApplicationDelegate` too late. This wrong behavior is introduced in #2768 (8ed544) by mistake. So we have to revert this part and move the registering right after creating event loop.
- Fix
- No

fix: drag and drop files on application icon in Dock to open not work.

---

Cargo.toml
src/window/macos.rs

By default, AppKit will helpfully collect any command line arguments that do not start with a dash and pass them to `application:openFiles:`. We do our own non-trivial command line parsing for our arguments and for Neovim, so we must disable this default behavior. (Otherwise, command lines like `neovide -- -c 'color blue'` will result in a modified buffer named "color blue".)
- Fix: Fixes #2609 https://github.com/neovide/neovide/issues/2629
- No

disable AppKit's command line processing

---

src/window/mouse_manager.rs

Fix the mouse scrolling when multigrid is disabled. The window id should always be 0, so use the `event_grid_id` function.
* fixes https://github.com/neovide/neovide/issues/2801
- No

fix: Mouse scrolling when multigrid is disabled

---

Cargo.lock
Cargo.toml

Also update the rest of the dependencies
Updates winit to 0.30.5, and the other dependencies to the latest allowed.
* fixes https://github.com/neovide/neovide/issues/2795
- No

fix: Update winit to 0.30.5

---

neovide-derive/src/lib.rs
src/renderer/mod.rs
src/settings/mod.rs
src/window/macos.rs
src/window/settings.rs
src/window/window_wrapper.rs
website/docs/configuration.md
website/docs/faq.md

Rename `neovide_transparency` to `neovide_opacity`. 
Changes to `neovide_transparency` will update `WindowSettings::opacity`. 
- Update all documentation and references to use `neovide_opacity`. 
- Rename `WindowSettings` transparency to opacity for consistency. 
- Add `alias` attribute to the `SettingGroup` macro.
- ~Update the test `test_read_initial_values` with alias.~
Test removed since aliases are excluded from `read_initial_values` to not trigger deprecation message at startup.
- Add deprecation message for settings with alias attribute. 
`Error: neovide_transparency has now been deprecated, use neovide_opacity instead.`
~I don't know if a deprecation message is needed and how to properly handle `neovide_transparency` deprecation, let me know.~
- Feature
- No
Feel free to edit or …

feat: rename and deprecate `neovide_transparency` to `neovide_opacity`

---

src/window/macos.rs
src/window/update_loop.rs

Generally, it is considered bad form for an application to un-cooperatively take the focus. However, for applications that are frequently launched from the terminal, they must strongly request focus because the terminal, in its ignorance, will not automatically yield.
- Fix: Fixes #2330 
- No

on macOS, activate when launched

---

Cargo.lock
Cargo.toml
src/main.rs
src/running_tracker.rs
src/settings/mod.rs
src/utils/test.rs

Remove `lazy_static` dependency and use `LazyLock` instead, which comes from the standard library. This is because the implementation comes from the standard library seems more reliable and stable than the one comes from a third-party crate.
No.

Remove `lazy_static`

---

src/window/macos.rs

- add a function to load the neovide icon
- set the application icon image on app launch
- Fix
- No
fixes #2831

bug: make sure to load and set the app icon for any context

---

src/renderer/rendered_layer.rs
website/docs/configuration.md

Fixes CI errors on main, and also adds the **Unrleased Yet** tag to the `neovide_floating_corner_radius` option.
- No

fix: ci build errors

---

Cargo.lock
Cargo.toml
src/cmd_line.rs
src/renderer/metal.rs
src/renderer/mod.rs
src/renderer/vsync/mod.rs
website/docs/command-line-reference.md

Add Metal renderer on macOS.
Currently this is a very naive implementation. I created this pr when the window at least shows things. I'm very unfamiliar with Metal development. So if you have any advice, I will extremely appreciate it.

feat: add support of Metal renderer on macOS.

---

src/editor/draw_command_batcher.rs
src/renderer/mod.rs

`win_viewport_margins` can be received before `win_viewport`, so initialize a zero sized window when that happens, so that further events can be processed in the correct order.
This replaces the broken custom window sorting that was implemented before in https://github.com/neovide/neovide/pull/2487
* Fixes https://github.com/neovide/neovide/issues/2838
* A better fix for https://github.com/neovide/neovide/issues/2464
- No

Initialize the window when 'win_viewport_margins' is received

---

src/window/window_wrapper.rs

If the scale factor for example, changes between prepare and render, then font change status was reset too early, and the following prepare step did not get a chance to process it. 
* fixes https://github.com/neovide/neovide/issues/2901
* fixes https://github.com/neovide/neovide/issues/2479
- No

fix: handle font changes during frame prepare

---

src/window/window_wrapper.rs

Winit 0.30.x does no longer send `WindowEvent::Resized` when the window is programmatically resized on Wayland, so we need to ensure that the render buffers are updated when that is done.
See: 
* https://github.com/rust-windowing/winit/issues/3919
- No

fix: setting of lines/columns on Wayland

---

Cargo.toml
src/window/window_wrapper.rs

The rounding when calculating the window size was wrong and caused an extra margin. This is now fixed
* Fixes https://github.com/neovide/neovide/issues/2367
* Fixes https://github.com/neovide/neovide/issues/2879
- No

fix: the calculation of the window size

---

src/renderer/mod.rs
src/renderer/rendered_window.rs

https://github.com/neovide/neovide/pull/2904 caused a regression, which manifests in a very similar crash that the PR was supposed to fix, but it happens for different reasons.
It turns out that `win_viewport_margins` can be sent in a different batch than the first `win_pos`. Which causes the flush to happen when the window is in an invalid state. Fix this by keeping track of this invalid state, and don't perform the actual flush for the window until `win_pos` has been received.
* Fixes https://github.com/neovide/neovide/issues/2910
- No

fix: crash when flushed before win_pos

---

src/renderer/grid_renderer.rs
src/renderer/mod.rs
src/renderer/rendered_layer.rs
src/renderer/rendered_window.rs
src/window/window_wrapper.rs

* Alternative implementation of https://github.com/neovide/neovide/pull/2883
* The `neovide_transparency` option now works for floating windows again, this was regressed in Neovide 0.13.2
* Simplified the transparency rendering so the transparency info is completely stored in the lines and the background clear. So there's no longer any skia layer based blending.
* Fixes https://github.com/neovide/neovide/issues/2884
NOTE:
This does not respect the documentation https://github.com/neovim/neovim/issues/24472#issuecomment-2563970117
> blend={integer}					[highlight-blend](https://neovim.io/doc/user/syntax.html#highlight-blend) [opacity](https://neovim.io/doc/user/syntax.html#opacity)
Override the blend level for a highlight group within the popupmenu
or floating windows. Only takes effect if …

fix: Neovide transparency works for floating windows again

---

src/renderer/grid_renderer.rs
src/renderer/mod.rs
src/window/settings.rs
src/window/window_wrapper.rs
website/docs/configuration.md

This feature adds the `neovide_text_background_opacity` setting and also changes how default background rendering is currently performed.
Additionally, this change _might_ solve some issues mentioned in https://github.com/neovide/neovide/issues/2471.
Side by side comparison with white desktop wallpaper and dark background.
```
neovide_transparency: 0.75
neovide_text_background_opacity: 0.75
no-multigrid: false
```
- Using `vim.o.winblend = 0`  for the default background on floating windows with multigrid enabled. 
- In this case, the floating background is `default * transparency`, which is neither fully opaque (as it should be) nor transparent (as it behaves in kitty/wezterm or without multigrid). 
Current workaround to achieve transparency is to set use this kind of configuration and …

feat: add normal opacity

---

src/window/macos.rs

During our changes to [fix](https://github.com/neovide/neovide/pull/2780) the opacity we also re-introduced a bug showing the [shadow](https://github.com/neovide/neovide/pull/2272) artifacts we already had in the past.
AT this moment we should update it adding the new `text_background_opacity` in the validation.

fix: add `text_background_opacity` in the opaque validation

---

Cargo.toml

chore: update `neovide-derive` to `0.1.1`

---

src/bridge/command.rs

Reopening #2949 , realized you need to specify `--shell-type login` to wsl.exe to not be a breaking change and accidentally closed the previous PR.
- Fixes #2941 
- No
- `nvim_cmd_impl` changed to use the syntax `wsl --shell-type login -- <bin> <args>` rather than `wsl $SHELL -lc <bin> <args>` which will still spawn the default shell.  The previous implementation actually spawns two shells.
- `create_platform_shell_command` changed to use `/bin/sh`, since non-POSIX shells might not have the `which` command
@fredizzimo 
> Thanks, but we can't change the shell to `sh`, becuase the user might have only configured their default shell and not `sh`. So, custom paths for example won't be set, which means that things like LSP won't work.
> 
> So, we need to find another way to do this, maybe …

fix: --wsl error if using non-POSIX shell as login shell

---

Cargo.toml

The next version of the `objc2` framework crates will have a bunch of default features enabled, see https://github.com/madsmtm/objc2/issues/627, so this PR pre-emptively disables them, so that your compile times down blow up once you upgrade to the next version (which is yet to be released, but will be soon).
- Fix / Other
- No

chore: prepare for `objc2` frameworks v0.3

---

src/window/macos.rs

Normally on macOS the case here wouldn't matter, but if you happen to be running a case sensitive file system (as I am) then the build fails because it can't find the icon file.
- Fix
- No

fix: build failure on case sensitive file system

---

src/renderer/fonts/caching_shaper.rs

Use the shape information from Swash for positioning the individual glyphs of a cluster, so that characters consisting of multiple glyphs are rendered correctly. Note that each cluster is still aligned to the grid.
The y-offset was also reversed and is now fixed. This could be seen as accents being too low, especially on capital letters. I haven't seen a bug report for it though.
* Fixes https://github.com/neovide/neovide/issues/2969
* Fixes https://github.com/neovide/neovide/issues/2539
- No

fix: Glyph offsets within a single cluster

---

src/bridge/command.rs

This causes the executable itself to be opened as a buffer...
The nvim binary was passed twice on the command line, which caused it to be opened as a buffer on WSL. The extra argument is now removed.
* Fixes https://github.com/neovide/neovide/issues/2609
- No

fix: Remove duplicate nvim bin argument for WSL

---

.github/workflows/build.yml

Statically link the MSVC runtime when deploying. This is only done for the deploy step in the CI, since statically linking is not necessary when building manually. And Skia does not provide a statically linked library, so the build times are much longer.
* Fixes https://github.com/neovide/neovide/issues/2948
**NOTE:** This is quite slow to run in the CI. It could maybe be changed to run only on main in the future. Or maybe we could build our own Skia binaries?
- No

fix: Statically link the msvc runtime when deploying

---

lua/init.lua
src/bridge/ui_commands.rs
src/cmd_line.rs
src/utils/mod.rs

Use `drop` for file drop instead of `edit`. The actual handling is also moved to lua, and the path escaped with `fnameescape`, due to drop not supporting `magic file=false`, https://github.com/neovim/neovim/issues/32351
This sets the arglist
* fixes https://github.com/neovide/neovide/issues/2629
It also fixes file drops when using WSL, the path is now properly converted.
It indirectly fixes customizing the drop behaviour, it's not documented, and a hack, but should do until we have a proper solution. The user can override `neovide.private.dropfile`
* https://github.com/neovide/neovide/issues/2991
@falcucci, can you test this on macOS that file drag still works, and that the arglist is now set and fixes #2629 
_A breaking change includes anything that breaks backwards compatibility either …

fix: Use drop for filedrop

---

src/window/keyboard_manager.rs

The IME input was sent unescaped, so special characters like `<` did not work. Modifiers were also not sent when using IME. This has been fixed by calling `format_key_text`
* Fixes https://github.com/neovide/neovide/issues/2975
* Most likely fixes https://github.com/neovide/neovide/issues/1866
- No

fix: Call format_key_text when delivering IME input

---

src/renderer/rendered_layer.rs
src/renderer/rendered_window.rs
src/window/mouse_manager.rs

The rounding done by the mouse manager was a bit inaccurate, which for example made it impossible to click the last column with some window sizes. This is now fixed
- No

fix: Fix mouse manager rounding

---

src/window/keyboard_manager.rs

- Fix
- No
fixes https://github.com/neovide/neovide/issues/3012

fix: remove redundant code for macos key event handling

---

src/window/mouse_manager.rs

This fixes a regression in https://github.com/neovide/neovide/pull/3015. It crashes when dragging to the left or top outside of a split window.
* fixes https://github.com/neovide/neovide/issues/3017
- No

fix: mousemanager regression

---

Cargo.lock
Cargo.toml
extra/osx/Neovide.app/Contents/Info.plist
neovide-derive/Cargo.toml

Bumps the version number to 0.14.1 and Neovide-derive to 0.1.2, since one of the dependencies has been updated since the last release.
- No

Release 0.14.1

---

src/window/window_wrapper.rs

- Feature
- No
Added acrylic blur for the background for Windows.
The implementation was made in winit library, just added the function call.

feat: background blur for Windows

---

.github/workflows/build.yml

The Ubuntu 20.04 Github runners are deprecated and will soon stop working. Currently they might randomly fail. So, this upgrades them to 22.04
- Yes, the Linux AppImage and binaries will stop working on some older Linux installations

chore!: upgrade the Ubuntu runners to 22.04

---

src/renderer/cursor_renderer/cursor_vfx.rs
website/docs/configuration.md

No particles were emitted when the buffer was scrolled so that the cursor moves a very small distance at a time. There were two bugs
1. Each cursor movement was processed in isolation. So, if the move was short enough, then the density setting might not be big enough to emit any particles. This is fixed by using an accumulator, so that a particle is emitted when the total distance traveled since the last particle is long enough.
2. The first particle emitted always got a lifetime of zero due to an off by one error
- No
Note: Because the exponential formula would be almost impossible to calculate with the accumulator,  the particle count formula has been changed from
```rust
let …
```

fix: particle vfx not being emitted for short travels

---

src/renderer/cursor_renderer/mod.rs

The front of the cursor immediately moves to the destination, for a much snappier feel.
One thing that always bothered me is the additional latency the cursor animation causes, sometimes it's enough to make you go one step too far when travelling by word or `f`. But I have been too lazy to bother investigating and fixing it.
The issue was that all parts of the cursor were animating, so there was always some time until you got a visual indication of what the destination is. This is fixed by always snapping the leading edge of the cursor to the destination, only animating the trail
I considered making this an option, but I don't see any reason why anyone would prefer the old behaviour. If it feels too fast, then the animating length can be increased. But the default is plenty enough, at …

feat: low latency cursor animation

---

src/renderer/cursor_renderer/cursor_vfx.rs
src/renderer/cursor_renderer/mod.rs

The point highlight cursor effects are now emitted when the cursor moves (jumps) instead of just when the mode changes. The effect is also now properly animated when the window is scrolled.
Finally, the lifetime is controlled by the `vfx_particle_lifetime` setting
- No
Technically it probably is, but since the effect has worked so poorly before I don't think it matters. The default lifetime is now much higher, it was 0.2 seconds before (hardcoded), and now 1.2 seconds (but configurable). And the same as for other particles, which I think makes sense, especially in combination with https://github.com/neovide/neovide/pull/3009

fix: point highlight cursor effects are properly emitted and animated

---

src/editor/mod.rs
src/renderer/cursor_renderer/mod.rs
src/window/settings.rs
website/docs/configuration.md

This makes it possible to disable the cursor hack from https://github.com/neovide/neovide/pull/753. 
The option is still enabled by default, but will be changed once Neovim deals with the busy state correctly. See
* https://github.com/neovim/neovim/issues/25980
* https://github.com/neovim/neovim/pull/29446
* https://github.com/neovim/neovim/pull/29447
However, if the flickering does not bother, especially if not using cursor animations, it can be disabled befor that.
These issues are fixed when the hack is disabled:
* https://github.com/neovide/neovide/issues/3000
* https://github.com/neovide/neovide/issues/2376
* https://github.com/neovide/neovide/issues/2516
* https://github.com/neovide/neovide/issues/2206
* https://github.com/neovide/neovide/issues/1665
- No

feat: make it possible to disable the cursor hack

---

src/editor/mod.rs

The z-index of the message window was wrong. Either because reading the source code wrong or a typo.
- No

fix: the z-index of message windows

---

src/renderer/mod.rs
src/renderer/rendered_layer.rs
src/renderer/rendered_window.rs

* fixes https://github.com/neovide/neovide/issues/2931
NOTE: That we currently don't draw a message separator, see https://github.com/neovide/neovide/issues/2237. And because we don't we need to draw the shadow when it's scrolled. It's a little bit more complex to draw the separator, we need to manually get the highlight group, and it also affect the message window scrolling, so it's left out from here and the 0.15.0 release.
- No

fix: don't draw shadows for the cmdline window unless it's scrolled and displaying a message

---

lua/init.lua

The tabs option takes a count not a boolean, so `--no-tabs` did not work. Furthermore, when tabs were used, the tabs were always opened after the first tab, now they are opened after the last.
- No

fix: file drop with open in tabs set to false

---

src/profiling/profiling_enabled.rs
src/renderer/animation_utils.rs
src/renderer/cursor_renderer/mod.rs
src/units.rs
website/docs/configuration.md

https://github.com/neovide/neovide/pull/3054 added low latency cursor movement, but unfortunately the new behaviour doesn't suite everyone. This therefore adds more configuration possibilities. 
The `neovide_cursor_animation_length`, now controls the animation length exactly in milliseconds. And the trail size controls how much faster front of the cursor moves in relation to the back. With the default value of 1.0 the front jumps to the destination immediately, with minimum lag. For a smoother experience you can lower the value at the cost of more lag.
* fixes https://github.com/neovide/neovide/issues/3059
- Yes, the meaning of the values changes, and the …

feat!: more configurable cursor animation

---

lua/init.lua

`nvim_exec` is deprecated, so use `nvim_exec2` instead.
- No

chore: Use nvim_exec2 instead of deprecated nvim_exec

---

src/bridge/command.rs
src/bridge/ui_commands.rs
src/cmd_line.rs
src/utils/mod.rs

When using WSL only the filename was escaped, and not other Neovim options like `--cmd "cd ~"`. This was a regression from https://github.com/neovide/neovide/pull/3045. But is fixed here, by using `shlex::try_join'
- No

fix: cmdline escaping when using WSL

---

src/renderer/box_drawing/renderer.rs
src/renderer/cursor_renderer/mod.rs

When a pixel position with a fraction very close to 0.5 was rendering, there's some inconsistency between how Skia (or the graphics drivers) rounds them and how Neovide does it. Therefore, always round non-antialiased coordinates as well.
* Fixes https://github.com/neovide/neovide/issues/3080
- No

fix: box drawing gaps due to inconsistent rendering

---

src/renderer/cursor_renderer/mod.rs
website/docs/configuration.md

The animation length for short movements was hardcoded to 0.04, and is now a configurable setting instead.
The unused `cursor_distance_length_adjust` setting was also removed
* fixes https://github.com/neovide/neovide/issues/3090
- No

feat: configurable short cursor animation

---

extra/osx/Neovide.app/Contents/Info.plist

Audio input is now possible on MacOS. As usual, the OS requires permission from the user on request, so nothing intrusive.
No

feat: audio input support on macos (#3070)

---

src/editor/draw_command_batcher.rs
src/editor/mod.rs
src/editor/window.rs

Refactor the code to pass the `DrawCommandBatcher` around instead of relying on interior mutability. This makes it easier to extend it with new functionality and also gets rid of the overhead of reference counting.
- No

chore: pass DrawCommandBatcher around instead of relying on interior mutability

---

lua/init.lua
src/bridge/events.rs
src/bridge/handler.rs
src/editor/draw_command_batcher.rs
src/editor/mod.rs
website/docs/SUMMARY.md
website/docs/api.md

Some plugins like blink.cmp (see https://github.com/Saghen/blink.cmp/issues/1247), is causing the cursor to flicker due lack of APIs on the Neovim side to support it completely. A temporary solution on the Neovide side is therefore implemented, which makes it possible to disable the redrawing and then re-enable it again.
The disabling is done by buffering on the editor side until it's re-enabled and sent to the renderer. All animations keep working even when the redraw is disabled.
Corresponding PR on the blink.cmp side https://github.com/Saghen/blink.cmp/pull/1582
- No

feat: add an API for disabling redraw

---

src/bridge/events.rs
src/editor/mod.rs
src/renderer/rendered_window.rs

This requires this corresponding PR to Neovim https://github.com/neovim/neovim/pull/31837 to enable the support, but works without.
This fixes a lot of multigrid issues like:
* Windows positioned slightly wrong
* Windows rendered in the wrong z-order
* We don't seem to have any issues open for this, but this also fixes most of the issues re-connecting to a remote nvim instance,
*  https://github.com/neovim/neovim/issues/30581
* ~https://github.com/neovim/neovim/issues/30582~ (not fixed)
* ~https://github.com/neovim/neovim/issues/30583~ (not fixed)
NOTE: Part of this PR was split out into 
* https://github.com/neovide/neovide/pull/3111
- No

Use composition information from Neovim

---

Cargo.lock
Cargo.toml
neovide-derive/Cargo.toml
website/docs/maintainer-cookbook.md

Bump the `neovide-derive` version number. 
Add instructions

fix: publishing to crates-io

---

src/bridge/events.rs
src/editor/style.rs

Add documentation comments to the variants of RedrawEvent based on Neovim's upstream documentation for UI events.
Sentences describing individual fields of an event have been moved to the field where I thought it made sense. I skipped most of the unused variants.
- No

doc: Add doc comments to RedrawEvent

---

src/window/mouse_manager.rs

This PR checks for window focus when showing/hiding the cursor to address the bug described in #2414.
- successful local build and install on macOS 14.6.1
- verified cursor went hidden when typing in neovide window
- verified cursor stayed visible when opening iterm window via hotkey and tabbing back
- verified cursor stayed visible when tabbing to different window and tabbing back
- No

Check for window focus when showing or hiding cursor

---

Cargo.lock
Cargo.toml
neovide-derive/Cargo.toml
src/settings/config.rs

The major ones
*  winit to 0.30.12
*  skia-safe 0.87.0
* glamour to 0.18.0
- No

chore: Upgrade and clean up dependencies

---

src/window/mouse_manager.rs

Allow mouse drags to continue even when the mouse has left the bounds of the window
- Fix
- No
Fixes https://github.com/neovide/neovide/issues/3198

Fix: drag events outside window

---

extra/osx/Neovide.app/Contents/Info.plist

- Feature
- No
This adds Go and Rust to the macOS Info.plist file so that Neovide can be set as the default editor for them.  I didn't see any particular ordering to the dicts in the file, so I just added these entries to the bottoms of each array.

Add Go and Rust to Info.plist

---

.github/workflows/build.yml

* Long paths are enabled for Git to allow Skia to build on windows without vendoring. And the result can therefore be cached
* Don't save caches on pull requests, we only have 10 GB available, and PRs can therefore evict the caches from main
* Only pull requests that updates dependencies would benefit from this anyway. I think we can change this to save only when cargo.lock or cargo.toml has been changed.
* Share the clippy and test caches
NOTE: Caches of nightly builds does not work well, due to new caches being needed each time the toolchain is updated. To fix this we should run an automated build every night. And maybe even generated nightly releases.
- No

chore: Improve the CI caching behaviour

---

.github/workflows/build.yml

#3226 had a couple of issues which are fixed here
1. It used `master` as ref instead of `main`. 
2. The cache was marked for saving for clippy, while only the test step should save
- No

Fix the CI caching behaviour from #3226
