neovide/neovide

README.md

This looks like a very interesting project!
I noticed a couple typos while skimming the readme file, hence this PR. I also changed the formatting in a few places, so feel free to reject this PR if you disagree with those changes.

Fix a few typos and inconsistencies in README.md

---

src/renderer/caching_shaper.rs

Fix conditional for MacOS emoji font

---

src/editor/cursor.rs
src/editor/mod.rs
src/renderer/mod.rs

Did some profiling on a more resource constrained machine and did some iterating on the build-draw-commands function. Profile shows a significant improvement especially at small font sizes.
Holding off on merging this as it has a pretty significant chance of causing problems.

profiling motivated perf improvements in build draw commands

---

.github/workflows/rust.yml

Simple GitHub workflow to generate Windows / macOS binaries. It will run with each push and create a binary against the master branch. Hope this helps to create releases :)

Github Workflow to generate binaries

---

README.md

I tried this on Docker and it successfully generates a binary. I don't have a way to test if the binary actually works.

Update README with build instructions for Ubuntu

---

src/bridge/keybindings.rs
src/window.rs

Hack to get more input events on Linux. 
Improves symptoms reported here: https://github.com/Kethku/neovide/issues/27

Linux input hack

---

src/bridge/keybindings.rs

Based on @awsomearvinder's PR: https://github.com/Kethku/neovide/pull/127
But doing a simpler change that's unlikely to cause any issues on Windows

Fix less than key on linux, simpler version

---

src/settings.rs

Fixes #139 
Uses the `exe` command to run the viml instead of `nvim_exec` which isn't currently available in Neovim 0.4.2.
Variables and functions created:

Modified 'setup_changed_listeners' for compatibility with 0.4.2

---

README.md

Hi
A nudge for user wanting to know more about this text engine.

doc: add link to HarfBuzz

---

src/bridge/mod.rs
src/main.rs
src/redraw_scheduler.rs
src/settings.rs
src/window.rs

Making PR to facilitate discussion

Structured settings

---

README.md

My build broke because I was missing libsndio-dev

Update Linux dependencies in README

---

src/bridge/mod.rs
src/editor/mod.rs
src/main.rs
src/settings.rs
src/window.rs

Allow the user to pass the window geometry as a command line flag `--geometry=<width>x<height>`

Allow user provided geometry

---

src/bridge/mod.rs
src/settings.rs

Added an command line argument to start the neovim process on the Windows WSL. I have little experience in Rust, so feel free to tell me if I did something wrong. This is my first pull request to an open source project, so any tips would be appreciated 😃.

Add WSL option for neovide on Windows

---

src/bridge/mod.rs

I'm not sure if all the running checks are necessary.

Signal bridge shutdown

---

src/bridge/events.rs
src/bridge/handler.rs
src/bridge/ui_commands.rs
src/editor/mod.rs

Fixes https://github.com/Kethku/neovide/issues/237

mouse configuration via mouseon mouseoff

---

src/bridge/events.rs
src/editor/cursor.rs
src/editor/mod.rs
src/redraw_scheduler.rs
src/renderer/cursor_renderer/cursor_vfx.rs
src/renderer/cursor_renderer/mod.rs
src/renderer/mod.rs
src/settings.rs
src/window.rs

I merged the master changes in and couldn't find any issues when running. Though I take it that it's not as simple as I think.

Switch to upstream skulpin

---

src/renderer/cursor_renderer/animation_utils.rs

Animation test

---

src/bridge/handler.rs
src/bridge/mod.rs
src/settings/mod.rs
src/settings/windows_registry.rs

Windows right click menu #94

---

src/bridge/events.rs
src/bridge/handler.rs
src/bridge/mod.rs

Rather than doing manual dynamic parsing of the channel list, this adds parsers for the values returned from list_chans. This is just a more principled and type safe approach than what existed before.

better parsing of client info

---

Cargo.lock
Cargo.toml
src/bridge/handler.rs
src/settings/from_value.rs
src/settings/mod.rs

This will include the fix: https://github.com/Rust-SDL2/rust-sdl2/pull/1027
That actuall update SDL2 to 2.0.12
And it will fix the IME not showing issue in Linux
Also refer to https://github.com/Rust-SDL2/rust-sdl2/pull/1025 also

Upgrade sdl2-sys to 0.34.3

---

Cargo.toml

Revert "Patch sdl sys"

---

Cargo.lock
Cargo.toml

rollback sdl2-sys

---

src/renderer/caching_shaper.rs

Solves an issue I had where it was selecting a font with the correct weight and style but wrong "stretch".

check font stretch property when selecting

---

src/bridge/mod.rs

Hi,
This PR addresses the WSL issues mentioned in #50. It works locally, but could probably use some more testing. Let me know what you think of the changes!
Edit: spoke too soon, release build didn't work. Removing `#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]` makes it work for some reason.

Fix --wsl option

---

src/bridge/events.rs
src/editor/cursor.rs
src/editor/mod.rs
src/editor/window.rs
src/renderer/cursor_renderer/mod.rs
src/renderer/mod.rs
src/renderer/rendered_window.rs

Implements smooth scrolling by positioning window textures inside of the window bounds according to a scrolled position which animates into place rather than jumping immediately. Implements and further details about the implementation can be found there https://github.com/Kethku/neovide/issues/62

Smooth scrolling

---

src/settings/mod.rs
src/window/sdl2/mod.rs
src/window/winit/mod.rs

solves https://github.com/Kethku/neovide/issues/356

add maximized command line argument

---

src/bridge/ui_commands.rs
src/main.rs
src/settings/mod.rs
src/window/sdl2/mod.rs
src/window/winit/mod.rs
src/windows_utils.rs

This fixes command line arguments on windows for version and help

Add version and help command line arguments

---

src/bridge/mod.rs

Set `termguicolors` to true

---

README.md

Quick fix for Arch users who encouter issue #527 
I expect a lot of Arch users will install neovide since DistroTube made a video about it recently.

Quick fix for Arch users

---

README.md

Also fixed a sequence break in Mac install instructions.

Update README.md to reflect changes in main branch.

---

Cargo.toml
src/bridge/mod.rs
src/editor/cursor.rs
src/editor/style.rs
src/renderer/cursor_renderer/mod.rs
src/renderer/fonts/caching_shaper.rs
src/renderer/mod.rs
src/renderer/rendered_window.rs
src/window/keyboard/settings.rs
src/window/window_wrapper/renderer.rs

This includes some clippy stuff and the eglCurrentDisplay patch as well.

Version check

---

src/window/window_wrapper/mod.rs

Fixes https://github.com/Kethku/neovide/issues/679.

Added trackpad support to scrolling/smoothscrolling in OpenGL branch

---

.vscode/launch.json
src/cmd_line.rs
src/editor/grid.rs
src/editor/window.rs
src/main.rs
src/renderer/cursor_renderer/cursor_vfx.rs
src/renderer/cursor_renderer/mod.rs
src/renderer/fonts/caching_shaper.rs
src/renderer/fonts/font_loader.rs
src/renderer/fonts/swash_font.rs
src/renderer/mod.rs
src/renderer/rendered_window.rs
src/window/mod.rs
src/window/window_wrapper/mod.rs

Introduces real honest to goodness font fallback

Font Fallback

---

src/window/window_wrapper/mod.rs

Fixes: https://github.com/Kethku/neovide/issues/582, 
Re-enables horizontal trackpad scrolling and swaps the scroll direction. This was actually the source of the "jarring" feeling I was experiencing in my original PR. I also raised the scroll threshold to -2.0 and 2.0 so its *slightly* less sensitive. 
Tested on macOS and arch linux with MacBook trackpad, Magic Mouse, and a "conventional" scrolling razer mouse.

Natural Horizontal scrolling

---

src/window/window_wrapper/keyboard_manager.rs

Supports handling dead keys more effectively
Reworks the keyboard input text code to handle deadkeys better
No this fixes broken input but should leave qwerty input pretty much the same

Keyboard deadkey handling

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Noticed that you need to manually add bug and feature labels to issues.  
This should fix this problem. 
Also Github didn't show me the feature request template option so I guess this header is needed.
Now hopefully works correctly

Add labels and fix feature req template

---

.github/PULL_REQUEST_TEMPLATE.yml

Just an update to the PR template that I think might be an improvement; feel free to close if not, of course.

doc(PULL_REQUEST_TEMPLATE): use checklist & comment

---

src/renderer/fonts/caching_shaper.rs
src/renderer/fonts/font_loader.rs
src/renderer/fonts/font_options.rs

Ref: #709
* Feature
(EDIT: I'm gonna put feature although it could also be seen as a fix . . . technicalities . . . )
* No

feat(fonts): add support for :b and :i in guifont

---

.github/workflows/build.yml
.github/workflows/clippy.yml

Add clippy check to CI

---

src/editor/grid.rs

This is small fix, correcting `cargo test` run.

Fix test function call

---

src/window/window_wrapper/mod.rs

set_inner_size was using LogicalSize from current physical size,
it was working fine only for scaling=1.
Removing this leaves unmaximizing to winit, which does it correctly.

fix(window_wrapper): Fix unmaximize behaviour

---

.github/workflows/clippy.yml

This is attempt to fix CI pipeline

fix(ci): Fix clippy

---

.github/workflows/build.yml
.github/workflows/snap.yaml

Fix build m1

---

Cargo.lock
src/renderer/fonts/caching_shaper.rs

Tweaks the vertical positioning of glyphs within a line to more closely match the expected positioning.

tweak vertical positioning

---

Cargo.toml

Fixes https://github.com/Kethku/neovide/issues/823

Fix Icon Metadata

---

Cargo.toml

Bump swash in Cargo.toml

---

Cargo.lock
Cargo.toml
src/cmd_line.rs
src/settings/mod.rs
src/settings/window_geometry.rs
src/window/settings.rs
src/window/window_wrapper/mod.rs

I couldn't figure out how to reopen the previous pull request(#665), so I just made a new one lol. Anyways, after the refactor done in #806, it looks like I can just check for the previous window setting while setting up global DEFAULT_WINDOW_GEOMETRY variable?

Remember window dimensions #622

---

src/main.rs
src/window/mod.rs
src/window/window_wrapper/keyboard_manager.rs
src/window/window_wrapper/mod.rs

- Split platform-dependent code into separate function
- Remove wrapper function `create_window`
- Move handle_new_grid_size where it belongs
- Codestyle
- Refactor
- No (It introduces no changes at all).

refactor: Refactor window module

---

Cargo.lock
Cargo.toml
src/bridge/create.rs

Swap to unforked nvim-rs

---

Cargo.toml

Add missing double quote

---

src/cmd_line.rs
src/main.rs
src/renderer/cursor_renderer/mod.rs
src/renderer/fonts/caching_shaper.rs
src/renderer/mod.rs
src/renderer/rendered_window.rs
src/settings/mod.rs
src/settings/window_geometry.rs
src/utils/dimensions.rs
src/utils/mod.rs
src/window/window_wrapper/mod.rs
src/window/window_wrapper/mouse_manager.rs

This PR introduces new type: `Dimensions`, for values like font_dimensions and other sizes. And combines paired values into single argument.
- Refactor
- No

Refactor grid conversions

---

Cargo.lock
Cargo.toml
snap/snapcraft.yaml
src/main.rs

Logs the version on startup and bumps the version to 0.8
- Other
- No

Log version

---

src/renderer/cursor_renderer/cursor_vfx.rs
src/renderer/cursor_renderer/mod.rs
src/renderer/grid_renderer.rs
src/renderer/mod.rs
src/renderer/rendered_window.rs
src/utils/dimensions.rs
src/window/window_wrapper/mod.rs
src/window/window_wrapper/mouse_manager.rs

Refactors the renderer a bit for readability
- Other
- No

Refactor Renderer

---

src/window/window_wrapper/mod.rs

fix(renderer): Force grid redraw on startup with --maximized flag

---

src/window/window_wrapper/mod.rs

fix: Allow resize at startup

---

.gitignore
src/cmd_line.rs
src/main.rs
src/window/settings.rs
src/window/window_wrapper/mod.rs

Adds an srgb setting to fix an issue on some amd machines
- Fix
- No

AMD Startup Fix

---

src/bridge/handler.rs
src/bridge/mod.rs
src/bridge/ui_commands.rs
src/main.rs
src/running_tracker.rs
src/window/window_wrapper/keyboard_manager.rs
src/window/window_wrapper/mod.rs
src/window/window_wrapper/mouse_manager.rs

Attempts to make keyboard input more stable
- Fix
- No

Refactor UI commands

---

src/editor/window.rs

- Refactor
- No breaking changes.
Have you considered not using Box there?

Remove unnecessary boxing

---

src/renderer/rendered_window.rs

Fix floating windows showing outside of neovide window

---

src/bridge/mod.rs
src/cmd_line.rs
src/main.rs

- Feature
- No
Adds command line argument for specifying neovim bin path.
Closes #1005

Add neovim_bin argument

---

Cargo.lock
Cargo.toml
src/settings/mod.rs
src/settings/window_geometry.rs
src/window/mod.rs
src/window/settings.rs

- Fix
- No
Adds `remember_window_position` setting.
Closes #887 
Works for me, but feel free to also test this yourself.

Add remember_window_position setting

---

src/renderer/fonts/caching_shaper.rs

Previously the font width was always rounded down to the nearest integer, which typically caused the fonts to look to squashed. To correct the issue a fudge factor, which scales the fonts so that the width is always an exact integer, was introduced.
Here's a comparison image, the top one is DejaVuSansMono NF:h11 without these changes, the middle one has the changes, the bottom row is the same font rendered with Windows 11 Notepad
A potential additional problem that I noticed is that we use the average glyph width for the metrics, while other code bases I have seen uses a wide character like `M` as the base. For example here https://github.com/microsoft/terminal/blob/main/src/renderer/dx/DxFontRenderData.cpp#L719

Fix the font spacing

---

src/window/keyboard_manager.rs

fix #243
no breaking changes
no breaking build, tested on windows 10.

fix #243 ime input support

---

README.md

- Improved documentation for building on MacOS
- No

Add instructions to create neovide.app for MacOS

---

src/bridge/handler.rs
src/renderer/fonts/caching_shaper.rs

Fixes event reordering which causes buffer render artifacts

---

src/editor/cursor.rs
src/editor/mod.rs
src/editor/window.rs
src/renderer/cursor_renderer/mod.rs

- Fix
Addresses #1021
Unsure, I changed the Cursor struct's "character" field to store a GridCell instead of a String in order to carry style information.

Fix cursor bold and italic rendering

---

src/renderer/grid_renderer.rs

Addresses https://github.com/neovide/neovide/issues/851
- Fix
- No

Fix grayed out text from lsp

---

src/bridge/events.rs
src/bridge/mod.rs
src/bridge/setup.rs

Alternate fix for clipboard in wsl

---

src/window/keyboard_manager.rs

It wasn't required outside, and this way code is cleaner.
- Codestyle
- No

refactor: Move call to SETTINGS.get inside should_ignore_input

---

src/bridge/command.rs
src/bridge/mod.rs
src/main.rs

@shaunsingh @fredizzimo in that case I vote we merge this.
- Fix
- Yes, please list breaking changes

fix for macos finder issue

---

src/renderer/fonts/caching_shaper.rs

- Other
- No
This is really not necessary.

cleanup: Remove super verbose logging from font_shaper

---

.github/workflows/build.yml
src/bridge/mod.rs
src/editor/window.rs

Fix broken CI

---

src/renderer/fonts/font_options.rs

Handle underscores in the font name as spaces

---

src/renderer/fonts/mod.rs
src/renderer/mod.rs
src/renderer/profiler.rs

- Feature
- No
I've quickly put together a display for FPS and a graph of frametimes, to help with testing performance,
It looks a bit rough, but serves it's function.

feat: profiler which displays frametime graph

---

snap/snapcraft.yaml

This is a draft that fixes the current issues with snapcraft. ~~Refactoring the dev packages out of the staging area may not be possible; last time this was attempted the build wouldn't work. Will test further.~~
Work on #1149
- Fix
- Refactor
- No

Snapcraft updates issue #1149

---

src/renderer/profiler.rs

- Fix (I can't compile on my computer, and this small code change fixed it)
- No

error: there is no argument named `min_ft` solved

---

src/window/mod.rs

Fixes #1216 Some command line arg not working 

---

Cargo.lock
Cargo.toml
src/cmd_line.rs
src/editor/cursor.rs
src/editor/grid.rs
src/editor/mod.rs
src/editor/window.rs
src/main.rs
src/renderer/cursor_renderer/mod.rs
src/settings/mod.rs

- Codestyle
- Other
- No
this PR just updates the dependencies + fixes a couple of clippy warning

Bump dependencies

---

src/bridge/mod.rs
src/cmd_line.rs

- Feature
- No
This PR brings with it the ability to open multiple files in multiple tabs, to improve the experience as a text editor

Open multiple files as Tabs

---

src/window/mod.rs

- Feature
- Codestyle
- Refactor
- Other
- No
Should fix #1436. Do not merge until issue author confirms fix.

Fix non consistent Wayland compositors

---

src/renderer/rendered_window.rs

Fixes broken smooth scrolling with multigrid, as seen in #1334.
Comparison video: (Before, After)
https://user-images.githubusercontent.com/83010835/184727581-bacd386a-8752-4c9c-9cca-54a935fc36e6.mp4
The cause of the issue is that a window's top line is changed before it is redrawn when the window's viewport updates.
If it has not been redrawn before neovide renders it, it would draw in the wrong position.
This PR keeps track of the top line, and renders the window at the old top line until the canvas has been redrawn.
- Fix
- No

Fix glitchy smooth scrolling (#1334)

---

src/window/mod.rs

This PR replaces the logic to get the framerate between event updates to use the higher framerate until a first render has been done when unfocusing. This makes the first render following an unfocus event use the faster framerate, fixing #1484.
The reordering solution suggested in #1484 does not seem to be enough since multiple events can be scheduled before the frame is redrawn in which case `focused` will be false and the slower framerate will be used.
Fixes #1484.
- Fix
- No

Keep the same framerate until a redraw when unfocusing the window.

---

src/renderer/rendered_window.rs

This pr fixes a regression in #1485 which breaks window viewports (sorry).
It is most noticeable when creating or moving windows.
Regression:
https://user-images.githubusercontent.com/83010835/184974106-07ca0de0-249f-45e9-a05a-1a2cbfd56332.mp4
This pr fixes it by only using the old draw position if the window is scrolling
https://user-images.githubusercontent.com/83010835/184974417-6ddadbea-3567-4e02-8ce5-8883776f073b.mp4
As far as I can tell this shouldn't cause any additional regressions, and the smooth scrolling fix from #1485 still works.
- Fix
- No

Fix regression in #1485

---

src/window/keyboard_manager.rs

- Fix
- No
This is the [solution proposed](https://github.com/neovide/neovide/issues/994#issuecomment-1063500913) by @Polish-Civil to [#994](https://github.com/neovide/neovide/issues/994).

Solved C-M not working in Linux

---

src/window/renderer.rs

Possible fix for https://github.com/neovide/neovide/issues/1518 and/or https://github.com/neovide/neovide/issues/1576.
No.

Schedule a redraw after a resize event

---

src/bridge/clipboard.rs
src/bridge/create.rs
src/bridge/events.rs
src/bridge/setup.rs
src/editor/window.rs
src/renderer/grid_renderer.rs
src/renderer/mod.rs
src/renderer/profiler.rs
src/renderer/rendered_window.rs

- Fix
- No
I was reading it without pretension, but the fact that some texts ends with ".", and others doesn't, and that some texts begans with a capital letter, and others doesn't, made me upset, haha.

fixing some text

---

src/bridge/setup.rs
src/frame.rs
src/main.rs
src/renderer/fonts/font_options.rs
src/renderer/grid_renderer.rs
src/settings/window_geometry.rs
src/window/settings.rs

This PR adds some minor refactors to the codebase, such as removing redundant borrowing, using more suitable combinators, and implementing proper traits for type conversion instead of simple struct methods.
- Codestyle
- Refactor
- No

Made small refactors

---

.github/workflows/build.yml
.gitignore

- Other: Appimage builds for Linux
- No

Appimage build

---

src/bridge/clipboard.rs

Fixes #1347
- No
This is my first time contributing in rust, so please let me know if I can improve it

Pass proper paste mode in case of wsl intergration

---

.github/workflows/build.yml

Other Include launcher assets in linux archive  
No

include launcher assets in linux archive

---

website/docs/faq.md

fix: faq doc

---

website/docs/index.md

fix: `Download for Windows` link

---

Cargo.lock
Cargo.toml

fix(deps): Update swash to fix crash at startup

---

src/cmd_line.rs
src/settings/config.rs
website/docs/config-file.md

Allows using `NEOVIDE_WSL` or config file to set wsl

---

Cargo.lock
Cargo.toml
snap/snapcraft.yaml
website/docs/config-file.md
website/docs/configuration.md

Just a "formalization" of the 0.11 release, so issues can be linked to it, and we can list what'll be breaking already. ~~I suppose we'll wait with this for some time after #1870 is be merged.~~ Feel free to get involved with testing, feedback and the like!
The list below doesn't list all changes made, but rather what'll be complemented by the autogenerated release notes.
- macOS: `<A-...>` keybindings previously only worked with dead keys. Now it's the other way around, they only work with _non_-dead keys. See https://github.com/neovide/neovide/pull/1899#issuecomment-1622968933. 
- Config file! https://neovide.dev/config-file.html
- Automatic OS theme change detection, if enabled! https://neovide.dev/configuration.html#theme
- Get running on Wayland again!
- IME support!

Release 0.11.0

---

src/window/keyboard_manager.rs

Improve the logging of keyboard events, everything we get from winit is logged.

chore: Better logging of keyboard events

---

src/window/mouse_manager.rs

Fix for https://github.com/neovide/neovide/issues/582
- Fix
- No

fix: fix horizontal scroll

---

neovide-derive/src/lib.rs
src/bridge/command.rs

It was hard to know exactly what output is causing startup failures, so this prints the stderr and stdout in addition to the error message.
- No

feat: Better reporting of unexpected output from neovim

---

Cargo.lock
Cargo.toml
neovide-derive/src/lib.rs
src/bridge/command.rs
src/bridge/mod.rs
src/bridge/setup.rs
src/bridge/ui_commands.rs
src/cmd_line.rs
src/error_handling.rs
src/event_aggregator.rs
src/main.rs
src/renderer/opengl.rs
src/settings/mod.rs
src/window/error_window.rs
src/window/mod.rs
src/window/window_wrapper.rs
src/windows_utils.rs

Depends on https://github.com/neovide/neovide/pull/2072
Some of the errors, like a channel being closed, are just ignored. While others are logged instead of panicking. This also gives better chance of recovery if something goes wrong. It could still be possible to save and exit from Neovim for example.
- No

fix: Fix some crashes that can happen during exit

---

website/docs/faq.md

Addresses https://github.com/neovide/neovide/issues/2010
- No

Add faq about x11 dpi sizing

---

src/renderer/rendered_window.rs
src/window/mouse_manager.rs

Fixes https://github.com/neovide/neovide/issues/1943
Fixes https://github.com/neovide/neovide/issues/1988
- Fix
- No

use grid 0 to report mouse events when not using multigrid

---

src/window/mod.rs

- Fix
- No
On Windows, the event loop calls `join()` on the render thread, but if the render thread is trying to do something that requires the Windows message pump to be running, this results in a deadlock. The easiest way to reproduce is to run `neovide -- -c "qa"`. On my machine, the event loop will try to join the render thread while the render thread is trying to set the window title, which completely hangs neovide. Since we're already polling `RUNNING_TRACKER` I just added a test for the render thread completion and only exit the event loop once the render thread is finished.

fix: event loop shouldn't join the render thread

---

src/cmd_line.rs
src/settings/window_size.rs
src/utils/ring_buffer.rs

- Fix
- No
Gives more context for errors such as #2132 so that the user can fix them.

Extra context if can't save to file

---

Cargo.lock
Cargo.toml

Updates to the latest winit version 0.29.4
Fixes:
* https://github.com/neovide/neovide/issues/2109
- No

fix: Update winit to 0.29.4

---

src/bridge/command.rs

The shlex crate does not handle windows path separator correctly, so don't try to use it on Windows, except when targeting WSL, and Windows paths are involved.
* Fixes https://github.com/neovide/neovide/issues/2201
- No

fix: Don't split the neovim-bin with shlex on non-wsl windows

---

src/settings/font.rs

fix: #2240 by swap item order in `FontDescriptionSettings`

---

src/renderer/fonts/font_options.rs
website/docs/config-file.md

feat: support all font weights and slants

---

src/editor/mod.rs

* Fix https://github.com/neovide/neovide/issues/2290
- No

fix: Error with guifont=*

---

Cargo.lock
Cargo.toml

Updates the depdendencies. The main thing being updating winit from 0.29.4 to 0.29.10, with a lot of bugfixes.
* Fixes https://github.com/neovide/neovide/issues/1237
The window shadows now works on Gnome https://github.com/neovide/neovide/issues/728, [sctk-adwaita](https://github.com/PolyMeilex/sctk-adwaita) was updated to 0.8.1
- No

Update dependencies and Winit to 0.29.10

---

src/bridge/command.rs

Addresses https://github.com/neovide/neovide/issues/2313. I'm only beginning to learn Rust, so I'm more than glad to make changes.
- Fix
- No

Fix shlex::join Deprecation Warning

---

src/cmd_line.rs
src/window/mod.rs
website/docs/command-line-reference.md

PR needed to complement #2168 
- Feature
- No

feat: implement dynamic window title visibility option

---

Cargo.lock
Cargo.toml
website/docs/command-line-reference.md
website/docs/configuration.md

Bump the version and update the docs.
- No

Bump version to 0.12.2

---

src/settings/font.rs

fix: font width can't be configured with config file

---

website/docs/SUMMARY.md

New doc page should be linked in Summary.md to be displayed in our website.
No
Tested locally

Update commands.md missing link

---

src/cmd_line.rs
src/settings/config.rs
website/docs/command-line-reference.md
website/docs/config-file.md

feat: tabs option as ENV variable and config file position + prefix cleanup for CLI argument

---

src/window/macos.rs
src/window/window_wrapper.rs

Note that the window will only actually be blurred if the underlying platform supports it
Could be considered either of these
- Fix
- Feature
- No

feat: Apply winit window blur setting on all platforms

---

src/bridge/api_info.rs
src/window/mod.rs
src/window/update_loop.rs

Quite heavy refactoring of the update loop, hopefully it's much easier to read and understand now. I'm planning to make a fix for a temporary freeze after the computer has been sleeping, but I wanted to get this refactored first for easier bisecting in case something breaks.
- No

chore: Refactor the update loop

---

src/bridge/api_info.rs
src/bridge/events.rs
src/cmd_line.rs
src/editor/grid.rs
src/editor/mod.rs
src/error_handling.rs
src/main.rs
src/renderer/animation_utils.rs
src/renderer/cursor_renderer/cursor_vfx.rs
src/renderer/cursor_renderer/mod.rs
src/renderer/fonts/font_options.rs
src/renderer/grid_renderer.rs
src/renderer/profiler.rs
src/renderer/rendered_window.rs
src/settings/from_value.rs
src/window/mod.rs

I run clippy with the latest nightly toolchain and fixed all the issues. I deleted some unused code, but whitelisted some that we are likely going to need in the future.
- No

chore: Fix clippy warnings

---

Cargo.lock
Cargo.toml
website/docs/configuration.md

Bump the version numbers and update the documentation for the 0.13.0 release

Release 0.13.0

---

src/renderer/mod.rs
src/window/window_wrapper.rs

- Fix
see https://github.com/neovide/neovide/pull/2596#issuecomment-2138361085
- No

handle scale_factor change early

---

website/docs/configuration.md

closes #2501 
relates #2565
- No

Add position_animation_length documentation

---

lua/init.lua
src/bridge/setup.rs
website/docs/configuration.md

This adds a new variable `neovide_version`. The channel information is also extended to contain the patch version.
* Fixes https://github.com/neovide/neovide/issues/2599
- No

feat: Provide a neovide_version variable

---

src/bridge/api_info.rs
src/bridge/ui_commands.rs
src/error_handling.rs
src/renderer/fonts/font_options.rs
src/settings/config.rs

style: simplify string formatting

---

src/renderer/fonts/font_options.rs
src/settings/font.rs
website/docs/config-file.md

Fix wrong toml format and improve font fallback logic

---

src/bridge/ui_commands.rs

fix: terminal file handler and UI command to use tabs based on settings 

---

.github/workflows/build.yml
macos-builder/run

feat: update deployment scripts for macOS .dmg creation

---

Cargo.lock
Cargo.toml
src/renderer/opengl.rs
src/renderer/rendered_layer.rs

Update some dependencies and bump the version number
- No

Release 0.13.2

---

src/renderer/fonts/font_options.rs

- Fix #2707 
This reverts some change from my previous pr, that was too naive :smile:
- No

fix: use pre-defined font weights only if user does not specify one

---

Cargo.lock
Cargo.toml
extra/osx/Neovide.app/Contents/Info.plist
website/docs/maintainer-cookbook.md

* Update some dependencies and bump the version number.
* Require macOS 12.0
- No

Release 0.13.3

---

Cargo.lock
Cargo.toml
src/renderer/animation_utils.rs
src/renderer/cursor_renderer/cursor_vfx.rs
src/renderer/cursor_renderer/mod.rs
src/renderer/grid_renderer.rs
src/renderer/rendered_window.rs
src/settings/window_size.rs
src/units.rs
src/window/mouse_manager.rs
src/window/window_wrapper.rs

Use Glamour instead of Euclid for Vide compatibility
- No

chore: Switch to glamour instead of euclid

---

Cargo.lock
Cargo.toml
src/clipboard.rs
src/main.rs
src/renderer/cursor_renderer/mod.rs
src/renderer/mod.rs
src/renderer/opengl.rs
src/renderer/vsync/macos_display_link.rs
src/window/error_window.rs
src/window/macos.rs
src/window/mod.rs
src/window/update_loop.rs
src/window/window_wrapper.rs

NOTE: Includes the 0.13.2 version bump, so don't merge yet until the release is out.
Also 
* Glutin 0.32,
* Glutin-winit 0.5.0 
* raw-window-handle 0.6.0
- No

chore: Update to winit 0.30.3

---

.github/workflows/build.yml
macos-builder/readme.md
macos-builder/run

docs: consolidate macOS build instructions and scripts

---

Cargo.lock
Cargo.toml
src/clipboard.rs
src/main.rs
src/renderer/cursor_renderer/mod.rs
src/renderer/mod.rs
src/window/error_window.rs
src/window/macos.rs
src/window/mod.rs
src/window/update_loop.rs
src/window/window_wrapper.rs

Update the wgpu branch to winit 0.30.3
- No

Update the wgpu branch to winit 0.30.3

---

Cargo.lock
Cargo.toml
src/profiling/profiling_disabled.rs
src/profiling/profiling_enabled.rs
src/renderer/grid_renderer.rs
src/renderer/mod.rs
src/renderer/rendered_window.rs
src/renderer/vsync/mod.rs
src/window/window_wrapper.rs

* Update tracy to the latest version, so that it's compatible with Vide
* Fix the `--no-vsync` mode
* Remove a duplicated `tracy_frame` event (vide takes care of that)
* Compile some external dependencies including vide and wgpu with optimizations even in debug mode. The Debug mode is still quite unusable, but that makes it a lot better already.
- No

chore(wgpu): Update tracy

---

Cargo.lock
Cargo.toml
src/editor/cursor.rs
src/renderer/cursor_renderer/mod.rs
src/renderer/mod.rs
src/renderer/profiler.rs

Enable cursor rendering and built-in profiler
- No

chore(wgpu): Enable cursor rendering and built-in profiler

---

website/docs/index.md

Fixes link for macos builds on the website
- Fix
- No
Fixes https://github.com/neovide/neovide/issues/2788

Fix macos download link

---

website/docs/faq.md

- No
Fixes https://github.com/neovide/neovide/issues/2565

Add faq entry for disabling all animations

---

Cargo.lock
Cargo.toml
src/renderer/cursor_renderer/mod.rs
src/renderer/grid_renderer.rs
src/renderer/mod.rs
src/renderer/profiler.rs
src/renderer/rendered_window.rs

- Fix
Updates vide and fixes the breaking api changes. Also fixes clippy errors that snuck in on stable
- No

(Chore) Update vide dependency in wgpu branch

---

Cargo.lock
neovide-derive/Cargo.toml
neovide-derive/src/lib.rs

Reported by sy in the discord. Thanks!
- Fix
- No

Update syn to 2.x to reduce package repetition in the binary

---

src/renderer/fonts/font_options.rs

- Fix
Now user can specify font style alone in config file, that will fallback to use first normal font family. I'm not sure where to throw the error..
Fix https://github.com/neovide/neovide/issues/2807
- Yes, fix the breaking change before?

fix: error if trying to specify font style overrides without a family

---

.nvim-dap.lua
lua/init.lua
stylua.toml

As mentioned in https://github.com/neovide/neovide/pull/2792#discussion_r1780046752, I would like to add a `.stylua.toml` file and format the Lua code.
I defined the style to be as close as possible to the existing code.
- Codestyle
- No

chore: add stylua.toml and format code

---

src/cmd_line.rs
src/settings/config.rs
src/window/mod.rs
src/window/window_wrapper.rs
website/docs/command-line-reference.md
website/docs/config-file.md

feat: add mouse cursor icon option

---

src/window/mod.rs

Fix #2329 
As mention in the issue, swapping the parameters fix the issue (at least on Hyprland).
- Fix
- No

Fix: --wayland_app_id doesn't work

---

src/renderer/rendered_layer.rs

Hello,
I would like to submit a fix for the rendering of rounded corners.
`rounded_silhouette` rendering was performed differently compared to the previous `silhouette` in `build_silhouette` which would completely hide my focused buffer in certain circumstances (multi-grid is enabled). 
Here is an example with neo-tree and a split buffer, where the bottom one is entirely hidden.
I'm not sure what is causing this issue.
It might be caused by one of my plugins, but this behavior was not present before this feature.
Also the issue is not consistent so unfortunately I was not able to create a reproducible scenario.
However, initializing the rounded path directly with `RRect` as it was done previously resolve the issue and keep the nice rounded corners.
I may have missed the reason for not …

fix: rounded corners rendering

---

Cargo.lock
Cargo.toml
src/renderer/d3d.rs

chore: update `skia-safe` version to `0.80.0`

---

website/docs/installation.md

docs: improve installation instructions and build steps for macOS

---

Cargo.lock
Cargo.toml
src/settings/config.rs
src/units.rs
src/window/macos.rs

-  Update all the dependencies to the latest version. This eliminates a few duplicate dependencies, but there there are still a lot of them left. 
- Winit has been updated to the latest 0.30.7 version
- No

chore: Update dependencies

---

src/bridge/clipboard.rs
src/bridge/handler.rs

fix: pasting ^M symbols from clipboard

---

src/bridge/clipboard.rs
src/bridge/handler.rs

Fix the code formatting of https://github.com/neovide/neovide/pull/2869
- No

chore: fix the formatting

---

src/window/window_wrapper.rs

Another attempt to fix the windows calculation. The solution in https://github.com/neovide/neovide/pull/2908, did not work, because the rounding needs to be done componen-wise. Because that wasn't working, `ceil` and `floor` had been swapped around to compensate. Finally, the tolerance was also wrong.
- No

fix: the calculation of the window size (attempt 2)

---

Cargo.lock
neovide-derive/Cargo.toml

chore: update `neovide-derive` to `0.1.1`

---

Cargo.toml

build: add exclusion for files in `website/` directory in cargo.toml

---

src/bridge/command.rs

- Fix
- No
fixes https://github.com/neovide/neovide/issues/2840

fix: execute login using zsh shell configuration

---

src/renderer/metal.rs

fix(metal): respect text_gamma and text_contrast setting

---

website/docs/config-file.md

docs: clarify link includes details about config file settings

---

.github/workflows/build.yml

https://github.com/rhysd/action-setup-vim/releases/tag/v1.4.1

ci: action setup vim has been fixed

---

website/docs/command-line-reference.md

cli-docs: add usage of frame on macOS

---

Cargo.lock
Cargo.toml
neovide-derive/Cargo.toml
src/editor/grid.rs

Update all dependencies
* fix https://github.com/neovide/neovide/issues/2981
- No

fix: Update dependencies

---

neovide-derive/src/lib.rs
src/renderer/mod.rs
src/settings/mod.rs
src/window/macos.rs
src/window/settings.rs
src/window/window_wrapper.rs
website/docs/configuration.md
website/docs/faq.md

Backport #2769 to main
@lucobellic

feat!: rename and deprecate `neovide_transparency` to `neovide_opacity`

---

Cargo.lock
Cargo.toml

* Fixes https://github.com/neovide/neovide/issues/2786
NOTE: Stile a draft, since there's no official swash release yet 
- No

Update swash to fix issues with some fonts

---

website/docs/installation.md

- tested with empty official Fedora docker image

Revisit Fedora installation.md notes.

---

Cargo.lock
Cargo.toml
extra/osx/Neovide.app/Contents/Info.plist

Update dependencies and bump the version number
- No

chore: Release 0.15.0

---

website/docs/config-file.md
website/docs/configuration.md

doc: remove unreleased yet tags

---

website/docs/config-file.md
website/docs/configuration.md

Fix markdown link for configuration doc

---

src/window/settings.rs
src/window/window_wrapper.rs
website/docs/configuration.md

Add simple fullscreen feature for MacOS and closes #2888.
No

Feature: add simple fullscreen feature for MacOS

---

Cargo.lock
Cargo.toml
extra/osx/Neovide.app/Contents/Info.plist
website/docs/configuration.md

Update dependencies and bump the version number

Release 0.15.1

---

src/settings/mod.rs
src/window/mouse_manager.rs

Fix formatting and clippy warnings
- No

chore: fix formatting and clippy warnings

---

.editorconfig
website/docs/configuration.md

Add an editor config for consistent line lengths. Most useful for the website, since we have had a few pull requests with the wrong line lengths for that.
The line lengths are configured to match our existing convention, so the lua files allow 120 characters, while rust and markdown only 100.
- No

chore: Add editorconfig

---

Cargo.toml
src/bridge/mod.rs
src/bridge/setup.rs
src/bridge/ui_commands.rs

* Don't use deprecated functions,.
* Use macros for cleaner syntax.
- No

refactor: Clean up various ways of calling nvim
